### ISSUE TITLE
Nested component Transitions render their fallback view on page refresh

### ISSUE THREAD

**Issue by PlGGS** [leptos-rs/leptos#1156] opened 2023-06-07 09:28 UTC
**Describe the bug**
Nested component Transitions render both their fallback as well as their content views on a page refresh

**Leptos Dependencies**
```toml
leptos = { git="https://github.com/leptos-rs/leptos", default-features = false, features = [
	"serde", "tracing",
] }
leptos_meta = { git="https://github.com/leptos-rs/leptos", default-features = false }
leptos_axum = { git="https://github.com/leptos-rs/leptos", optional = true }
leptos_router = {  git="https://github.com/leptos-rs/leptos", default-features = false }
```

**To Reproduce**
1. Create two components with transitions for rendering async content
2. Nest one of the components within the other
3. Build and watch project
4. Refresh the page to see both the fallback and the content of the inner component's Transition

**Expected behavior**
I expected both components to render their content as normal

**Screenshots**
My inner component: (Ignore the unnecessary braces warning. That's a separate issue, because those braces are  necessary)
![image](https://github.com/leptos-rs/leptos/assets/20197872/6592712c-d6e1-4b94-8eb5-2f7a5cc48417)

DOM before refresh:
![image](https://github.com/leptos-rs/leptos/assets/20197872/e01e1158-fc04-4fc6-9dba-74e260d8b9a4)

DOM after refresh:
![image](https://github.com/leptos-rs/leptos/assets/20197872/434e4965-776f-4f26-a308-75c56e43c986)

It goes from looking like this:
![image](https://github.com/leptos-rs/leptos/assets/20197872/76a9ca47-54e5-452a-a952-d90dfc70150f)

To this:
![image](https://github.com/leptos-rs/leptos/assets/20197872/2fe81474-9ea5-4beb-893f-658aa0b07df2)

Thanks!

**Comment by PlGGS** [comment] 2023-06-07 09:40
Here's what the DOM looks like with my current workaround: <Transition fallback=move || view! {cx, **{}** }>
![image](https://github.com/leptos-rs/leptos/assets/20197872/cb2cbe6f-0cd6-4a19-a92f-320104f2dc6b)

**Comment by PlGGS** [comment] 2023-06-07 10:13
Update: This was apparently only an issue as of Firefox version 112.0.2. I just tried this in Chromium and then updated Firefox, and they both worked without a problem.

**Comment by PlGGS** [comment] 2023-06-07 10:28
Nevermind, it's now only occuring on this other nested component in my project:
![image](https://github.com/leptos-rs/leptos/assets/20197872/5cfd0dda-d0ff-4d31-868f-6d43b7e85680)

DOM after refresh:
![image](https://github.com/leptos-rs/leptos/assets/20197872/0377fc42-80e6-488e-86cc-8a6493b4692a)

It happens in both Chromium and Firefox, and now it's happening on the initial page load too.

**Comment by gbj** [comment] 2023-06-07 13:16
Could you please paste the text for your example in here, so that I don't have to re-type it from the screenshot? Thanks!

**Comment by gbj** [comment] 2023-06-07 20:44
> Ignore the unnecessary braces warning. That's a separate issue, because those braces are necessary) 
Just for what it's worth, that entire `view` macro invocation seems to be unnecessary... It is the same as just saying `existing_user`. In which case, assigning to `existing_user` and then immediately returning it also seems to be unnecessary... just return the closure itself. In which case, in fact you seem to have unnecessary nested closure, and can just use the inner closure. I don't *think* any of that is related to the actual issue, but as I said, just for what it's worth.

**Comment by PlGGS** [comment] 2023-06-07 21:43
> Could you please paste the text for your example in here, so that I don't have to re-type it from the screenshot? Thanks!

It's a lot, so here's [a CodeSandbox](https://codesandbox.io/p/sandbox/magical-water-ochsh1?file=%2Fsrc/app.rs) with everything necessary to reproduce the bug. My actual repo is currently private because it's a school project, so I'd rather just share this temporarily. It's currently not building in CodeSandbox due to Tokio CORS, but the offending components are in app.rs. Thanks again!

**Comment by PlGGS** [comment] 2023-06-07 21:46
> > Ignore the unnecessary braces warning. That's a separate issue, because those braces are necessary)
> 
> Just for what it's worth, that entire `view` macro invocation seems to be unnecessary...

Oh thank you! I was basing my components off of [this component](https://github.com/leptos-rs/leptos/blob/3d75c71bfabc229ced6b22b862f65467977307e8/examples/session_auth_axum/src/todo.rs#LL294C21-L294C21) in the session_auth_axum example example, so I didn't realize I could simplify it further. The bug still exists with simplified components.

**Comment by gbj** [comment] 2023-06-10 19:42
Ah okay so it took me a while to figure out what exactly what going on here. As far as I can tell, if you have a nested `<Suspense/>` or `<Transition/>` such that the two exist in a data "waterfall," it causes a hydration issue.
```
- load resource A
- Suspense A
  - load resource B
  - {display A}
  - Suspense B
    - {display B}
```

Simply removing the inner `<Transition/>` in `<AuthorLink/>` in this case removes the issue for me. 

I haven't looked at it in much more depth but will think about whether there's a better way to handle this. It may also be a timing issue related to when the two separate requests load.

In general it's best to structure data loading such that these waterfalls don't happen, in any case; i.e., to load the posts, and to load the relevant user avatar data alongside them, so that you only have one request to the server/DB instead of many cascading requests.

**Comment by gbj** [comment] 2023-06-21 19:59
Just confirmed that #1214 does in fact fix this, which is great. 

@PlGGS to the extent that it's useful or interesting to know, I noticed a couple places (`UserProfileLink` and `UserFirstAndLastName`) where you have access to `user` every time you use them, but instead of passing `user` as a prop you pass `user.id` and then create a new resource to read the user's info from the database. This means you have like 4x the number of network requests/database reads you need, plus a bunch of boilerplate in your templates — you can just pass `user` directly, save the requests and DB reads, and remove a bunch of `view!` cruft! 😄 

Thanks for finding this bug. It turned out that this week I needed to fix it in my own app, so I did the work and it turned out it was the same work.

**Closed** 2023-06-21 20:40 UTC
Labels: bug
