### ISSUE TITLE
errors_axum compile error: `hydrate` and `ssr` enabled as features

### ISSUE THREAD

**Issue by agilarity** [leptos-rs/leptos#917] opened 2023-04-21 19:21 UTC
Run `cargo make test -p errors_axum` from `leptos/examples` to reproduce.

**Comment by gbj** [comment] 2023-04-21 19:22
Closing as a duplicate of #916, let's just keep it to one report for any of the examples so I can answer you in one place.

**Closed by gbj** 2023-04-21 19:22 UTC

**Comment by agilarity** [comment] 2023-04-21 19:27
Sure thing. I will add similar errors to #916.

Thank you for looking into this so quickly.
