### ISSUE TITLE
examples/todomvc leaks?

### ISSUE THREAD

**Issue by takeisit** [leptos-rs/leptos#706] opened 2023-03-19 10:39 UTC
Forgive me if I am wrong.
My understanding is that ```Signal```s are disposed only when their ```Scope``` is disposed.
In ```examples/todomvc```, I think that the ```RwSignal```s (title/completed fields) of removed ```Todo```s never been disposed while the app is running, because their ```Scope``` is almost root of the app.

If so, my project contains the similer pattern and thus has same problem.
Are there ways to remove ```(Rw)Signal``` from ```Scope``` before ```Scope``` disposing, or something else to work around leak?

**Comment by gbj** [comment] 2023-03-19 11:10
To put it a slightly different way: the reactive runtime continues to own the value of your signal until the `Scope` in which it was created is disposed.

This means:
1. If you create and destroy a large number of signals in the root scope, memory usage will steadily increase, and not be reclaimed until you leave the page
2. `Drop` won't be run on the signal value

Solutions:
1. Creating signals in a lower scope like in a row of a `<For/>` component
2. I add a manual `.dispose()` method on signals, which detaches them from their dependencies, takes and drops their value, and frees up their space in the reactive system

Option 1 will work in many cases. Option 2 sounds like a good idea to me and will probably help us with memory usage a bit in other benchmarks.

**Comment by takeisit** [comment] 2023-03-19 12:40
@gbj Thanks for your response. 
```.dispose()``` of Option 2 is what I want!

**Comment by gbj** [comment] 2023-03-20 01:41
Yeah, makes sense. I've added a `.dispose()` function to each signal as part of a SignalDispose trait. That should do the trick, I think.

**Comment by lukechu10** [comment] 2023-05-12 14:38
Although we have `.dispose()` now, I don't think the issue has been fixed for the `todomvc` example.

I did a similar test on the official js-framework-benchmark implementation here https://rawgit.com/krausest/js-framework-benchmark/master/frameworks/keyed/leptos/index.html and observed the same issue.

Here's a video recording:

https://github.com/leptos-rs/leptos/assets/37006668/6756d6c4-49e7-40f1-b46d-55e54d552d6c


Note that the memory used by the `ArrayBuffer` which backs the WASM memory grows every time 1000 rows are added and cleared. Although WASM memory cannot currently shrink, it should not grow, or at most, grow only a little bit the second time 1000 rows are added and cleared.

**Comment by lukechu10** [comment] 2023-05-12 14:41
I'm struggling to think of a nice way to fix this without having to manually calling `dispose` which would be boilerplate-y and easy to forget about. Perhaps someone else has a better idea!

**Comment by gbj** [comment] 2023-05-12 14:57
@lukechu10 Just for the sake of clarity, the `js-framework-benchmark` implementation hasn't actually been updated to use `.dispose()` here, so I think the behavior you're seeing is expected. I'll update it when I release our next version. 

Are you saying that you're still seeing a leak in the `todomvc` example though?

Definitely the main issue with this particular reactive implementation is the possibility of leaks when scopes are not disposed, or when signals are created in the root scope (like in the `todomvc` or `js-framework-benchmark` examples) but never disposed. Control flow components have to be written to manually dispose of the child scopes they create.

This is a big part of why I'm looking at shifting over to Solid's model of reactive ownership (see #918), as they would remove the need for explicit `Scope` management entirely.

In the case of signals created and stored at a root level though I think the manual disposal would be necessary. Very open to any ideas.

**Comment by lukechu10** [comment] 2023-05-12 16:03
> Are you saying that you're still seeing a leak in the `todomvc` example though?

I haven't managed to test it just yet but I don't see any `.dispose()` anywhere in the source code so I'd imagine the issue is not fixed.

> This is a big part of why I'm looking at shifting over to Solid's model of reactive ownership (see #918), as they would remove the need for explicit `Scope` management entirely.

Now that I think of it, I'm worried that this might make this issue even worse since it would be harder to see which scope each signal belongs to.

The way that I originally solved the problem of too long-lived `cx` inside conditionally rendered children in Sycamore was to simply check if the `cx` identifier was anywhere inside the `TokenStream` of the dynamic expression. This of course was a little bit too conservative since it would introduce extra child-scopes when they weren't always necessary and also was possible to work around, simply by having a `let other_cx = cx;` somewhere and using `other_cx` instead, but in practice worked very reliably.

However, merging `Scope`s with reactive nodes definitely is a pretty nice solution to this as well!



One thing I was looking into was to emulate SolidJS's `createStore` which would eliminate the need for nested signals. One way this could be achieved in Rust would be to use the lens pattern like in https://crates.io/crates/lens-rs and would actually be quite similar to what I believe `create_slice` does right now except we don't have to duplicate get and set and would also allow us to do change detection based on the path instead of relying on `PartialEq`.

**Comment by gbj** [comment] 2023-05-12 21:06
> > Are you saying that you're still seeing a leak in the `todomvc` example though?
> 
> I haven't managed to test it just yet but I don't see any `.dispose()` anywhere in the source code so I'd imagine the issue is not fixed.

Oh got it. This sounds like something I would do, yes. (Implement what's needed for the solution but forget to actually add it to the example.) 

And indeed the PR adding the feature to close this doesn't actually do it in `todomvc`. I'll reopen this to remind myself.

> > This is a big part of why I'm looking at shifting over to Solid's model of reactive ownership (see #918), as they would remove the need for explicit `Scope` management entirely.
> 
> Now that I think of it, I'm worried that this might make this issue even worse since it would be harder to see which scope each signal belongs to.

Fair. This particular "top-level signal creation" issue wouldn't go away. The owning scope is the parent effect/memo, which isn't always obvious because the renderer introduces some hidden effects.

It's easy-ish for me at least to track them because the node IDs are just slotmap IDs so fairly easy to get an ancestry chain and debug ("Owner is node 1, then 2, then 3") but harder for a typical user of course.

> The way that I originally solved the problem of too long-lived `cx` inside conditionally rendered children in Sycamore was to simply check if the `cx` identifier was anywhere inside the `TokenStream` of the dynamic expression. This of course was a little bit too conservative since it would introduce extra child-scopes when they weren't always necessary and also was possible to work around, simply by having a `let other_cx = cx;` somewhere and using `other_cx` instead, but in practice worked very reliably.

Hm this is interesting. I guess it works with the macro but not with a builder.

> One thing I was looking into was to emulate SolidJS's `createStore` which would eliminate the need for nested signals. One way this could be achieved in Rust would be to use the lens pattern like in https://crates.io/crates/lens-rs and would actually be quite similar to what I believe `create_slice` does right now except we don't have to duplicate get and set and would also allow us to do change detection based on the path instead of relying on `PartialEq`.

This is very interesting! I definitely like the lens approach, which I hadn't seen before. People have pointed out that `create_slice` is fine except that if you have a very large number of nodes it will need to re-run those memo checks, which isn't free.

**Closed** 2023-05-15 18:53 UTC
Labels: enhancement
