### ISSUE TITLE
leptos_meta components inside a <Suspense/> do not update the DOM

### ISSUE THREAD

**Issue by Niedzwiedzw** [leptos-rs/leptos#404] opened 2023-01-29 17:31 UTC

**Comment by gbj** [comment] 2023-01-30 00:06
This doesn't actually appear to be the case. Here's a very simple "doesn't reproduce." This correctly sets the title and meta tag in the actual DOM (i.e., in the inspector) once the Wasm has loaded and it hydrates, although it doesn't (and can't) insert them into the initial head. 

Since we were talking about this on Discord and I suggested you open this issue, I'm going to close it.

For anyone who's reading this and is curious: Using streaming SSR, we don't wait for resources to resolve before we begin streaming HTML, but send them in a separate chunk once they've resolved. This means that meta tags can't be sent in the `<head>` if they're under a `<Suspense/>`, because the `<head>` has already been sent. Granted that this is one of the tradeoffs between streaming and plain-`async` SSR rendering.

```rust
#[component]
pub fn App(cx: Scope) -> impl IntoView {
    // Provides context that manages stylesheets, titles, meta tags, etc.
    provide_meta_context(cx);

    let res = create_resource(cx, || (), |_| async move { true });

    view! {
        cx,

        <Suspense fallback=move || view! { cx, <p>"Fallback"</p> }>
        {move || res.read().map(|val| view! { cx,
            <pre>{val}</pre>
            <Title text="Welcome to Leptos"/>
            <Meta name="description" content=val.to_string()/>
        })}
        </Suspense>
    }
}
```

**Closed by gbj** 2023-01-30 00:06 UTC
Labels: bug, meta
