### ISSUE TITLE
Derived Memo not triggering correctly when not rendered

### ISSUE THREAD

**Issue by fdietze** [leptos-rs/leptos#3339] opened 2024-12-09 07:38 UTC
**Describe the bug**
A derived Memo doesn't recompute correctly. Rendering it makes it trigger correctly.

**Leptos Dependencies**

```toml
leptos = { version = "0.7.0", features = ["csr", "nightly"] }
```

**To Reproduce**

```rust
#[component]
fn App() -> impl IntoView {
    let (input, set_input) = signal(0);
    let first_memo = Memo::new(move |_| input() == 1);
    let second_memo = Memo::new(move |_| first_memo());

    let (submitted_value, set_submitted_value) = signal(false);

    let submit = move || {
        set_submitted_value(second_memo());
    };

    view! {
        Press these buttons in order to reproduce the bug:
        <div>
            <button on:click=move |_| { set_input(1) }>1</button>
            <button on:click=move |_| { submit() }>submit</button>
            <button on:click=move |_| { set_input(2) }>2</button>
            <button on:click=move |_| { set_input(3) }>3</button>
            <button on:click=move |_| { submit() }>submit</button>
        </div>
        Input:
        {move || input()}
        <br />
        First Memo:
        {move || first_memo()}
        <br />
        <Show when=|| {
            false
        }>
            Second Memo: {move || second_memo()}<br />
            Enabling this Show, makes the second memo trigger correctly.
        </Show>
        <br />
        Submitted:
        {move || submitted_value()}
    }
}
```

1. Press the buttons in order.
2. BUG: the submitted value is `true`, but should be `false`
3. Change the `false` in `<Show>` to `true`, to render `second_memo`
4. Press the buttons in order.
5. The submitted value is correct: `false`

**Expected behavior**
Derived memos should always have the latest state available when their inputs change.

**Comment by gbj** [comment] 2024-12-09 12:49
Thanks! 

As a note to myself: the problem occurs specifically when the first memo is triggered twice before the second memo is ever read again, so that by the time `.update_if_necessary()` runs on the second memo during its read, its parent has already marked itself clean again. The second memo should probably have been marked dirty when the first one changed.

**Comment by gbj** [comment] 2024-12-12 23:59
The issue here turns out to be super simple and a regression in my rewrite of the reactive graph for 0.7: the `Memo::mark_check` function should only mark a `Memo` as being in the `Check` state if it isn't already `Dirty`, which is a stronger claim. The one-line change in the PR (plus regression test) close this issue.

**Closed** 2024-12-16 14:10 UTC
Labels: bug
