### ISSUE TITLE
Nested Suspense ignores SSR Mode and breaks Hydration

### ISSUE THREAD

**Issue by luxalpa** [leptos-rs/leptos#2561] opened 2024-04-25 17:02 UTC
**Describe the bug**
When using a Suspense within another Suspense with PartiallyBlocked SSR mode and two blocking resources, it will only block for the outer one, but not wait for the inner one. Furthermore, a <For> component (possibly others) that renders after the Suspense won't hydrate properly and instead create `<DynChild>` and `<>` comment nodes.

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

For example:
```toml
leptos = { version = "0.6.11", features = ["nightly"] }
leptos_meta = { version = "0.6.11", features = ["nightly"] }
leptos_actix = { version = "0.6.11", optional = true }
leptos_router = { version = "0.6.11", features = ["nightly"] }
leptos_dom = "0.6.11"
leptos_reactive = { version = "0.6.11" }
leptos_macro = { version = "0.6.11" }
serde = "1.0.198"
```

**To Reproduce**

```rs
use leptos::*;
use leptos_meta::*;
use leptos_router::{Route, Router, Routes, SsrMode};
use std::time::Duration;

#[component]
pub fn App() -> impl IntoView {
    provide_meta_context();

    view! {
        <Router>
            <div>
                "Hello World"
                    <Routes>
                        <Route path="/" view=|| {
                            view! {<FrontPage />}
                        } ssr=SsrMode::PartiallyBlocked />
                    </Routes>
            </div>
            <For each=move || vec![1, 2, 3] key=|k| *k children=|i| {
                view! {
                    <div>
                        {i}
                    </div>
                }
            } />
        </Router>
    }
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone)]
pub struct UserData {
    name: String,
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone)]
pub struct SiteData {
    contents: String,
}

#[server]
pub async fn get_user_data() -> Result<UserData, ServerFnError> {
    return Ok(UserData {
        name: "Luxalpa".to_string(),
    });
}

#[server]
pub async fn get_site_data() -> Result<SiteData, ServerFnError> {
    use actix_web::HttpRequest;
    use leptos_actix::extract;

    let req: HttpRequest = extract().await.unwrap();
    println!("Method: {:?}", req.method());

    return Ok(SiteData {
        contents: "Welcome to Leptos".to_string(),
    });
}

#[component]
pub fn FrontPage() -> impl IntoView {
    let res = create_blocking_resource(|| (), |_| async move { get_user_data().await.unwrap() });

    let contents = move || {
        res.with(|data| {
            let Some(data) = data.as_ref() else {
                return ().into_view();
            };

            let res2 =
                create_blocking_resource(|| (), |_| async move { get_site_data().await.unwrap() });

            // spawn_local(async move {
            //     let site_data = get_site_data().await.unwrap();  // <- this code is also broken, but I'll probably file a separate issue
            //     println!("Site Data: {:?}", site_data);
            // });

            let name = data.name.clone();

            (view! {
                <div>
                    <Suspense>
                        {move || res2.get().map(|data| data.contents)}
                    </Suspense>
                    {name}
                </div>
            })
            .into_view()
        })
    };

    view! {
        <div>
            <Suspense>
                {contents}
            </Suspense>
        </div>
    }
}
```

**Expected behavior**
Render the entire HTML first instead of rendering it later. Properly hydrate the created components

**Additional context**
My outer suspense / resource is loading UserData depending on whether the user is logged in or not. Then the inner suspense / resource is loading some application data that is only allowed to be loaded if the user is logged in. Unfortunately it seems that I cannot avoid nesting Suspense's here, as I can't load all possible userdata on the outer context, and if I load only the data necessary for the current page, then it won't work if the user starts on a different page but then navigates to this one. I have a large app and several pages have this issue, so any hacky workaround will also involve tons of work.

**Comment by gbj** [comment] 2024-04-25 17:35
Hm. This one does seem to be fixed by https://github.com/leptos-rs/leptos/pull/2284, which I closed because I thought it broke other things. It may be worth testing your full example against that branch to see if it does break other things. I can revisit it.

The current Suspense system is very fragile and is one of the things that is definitely being improved in 0.7 wheni it comes. Sorry for the pain for now.

**Comment by gbj** [comment] 2024-09-26 01:58
As of #2995 this works on 0.7/git main as the example below.

```rust
pub fn shell(options: LeptosOptions) -> impl IntoView {
    view! {
        <!DOCTYPE html>
        <html lang="en">
            <head>
                <meta charset="utf-8"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <AutoReload options=options.clone()/>
                <HydrationScripts options/>
                <MetaTags/>
            </head>
            <body>
                <App/>
            </body>
        </html>
    }
}

#[component]
pub fn App() -> impl IntoView {
    view! {
        <Router>
            <main>
                <FlatRoutes fallback>
                    // We’ll load the home page with out-of-order streaming and <Suspense/>
                    <Route path=StaticSegment("") view=HomePage ssr=SsrMode::PartiallyBlocked/>
                </FlatRoutes>
            </main>
        </Router>
        <button on:click=|_| leptos::logging::log!("hydrated correctly")>"Click"</button>
    }
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone)]
pub struct UserData {
    name: String,
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone)]
pub struct SiteData {
    contents: String,
}

#[server]
pub async fn get_user_data() -> Result<UserData, ServerFnError> {
    tokio::time::sleep(std::time::Duration::from_secs(1)).await;
    return Ok(UserData {
        name: "Luxalpa".to_string(),
    });
}

#[server]
pub async fn get_site_data() -> Result<SiteData, ServerFnError> {
    tokio::time::sleep(std::time::Duration::from_secs(1)).await;

    return Ok(SiteData {
        contents: "Welcome to Leptos".to_string(),
    });
}

#[component]
pub fn HomePage() -> impl IntoView {
    let res = Resource::new_blocking(
        || (),
        |_| async move { get_user_data().await.unwrap() },
    );

    let contents = move || {
        Suspend::new(async move {
            let data = res.await;

            let res2 = Resource::new_blocking(
                || (),
                |_| async move { get_site_data().await.unwrap() },
            );

            view! {
                <div>
                    <Suspense>{move || res2.get().map(|data| data.contents)}</Suspense>
                    {data.name}
                </div>
            }
        })
    };

    view! {
        <div>
            <Suspense>{contents}</Suspense>
        </div>
    }
}
```

Note that nesting the creation of the second blocking resource inside the Suspense will still not block for the second resource. This is more or less working as designed, because using the inner Suspense says "ok, here's another chunk that can be streamed separately."

I'm okay with this, because 0.7 also makes it trivial for a resource to wait for another resource *without* dealing with nested Suspense like this: simply hoisting `res2` up above the first `Suspense` and having it wait for `res` will yield the desired behavior. Hoisting resources to the highest level possible is desirable because it means they begin loading ASAP, so I'm satisfied with this pattern.

```rust
    let res = Resource::new_blocking(
        || (),
        |_| async move { get_user_data().await.unwrap() },
    );
    let res2 = Resource::new_blocking(
        || (),
        move |_| async move {
            res.await;
            get_site_data().await.unwrap()
        },
    );
```

**Closed by gbj** 2024-09-26 01:58 UTC
Labels: bug

**Comment by luxalpa** [comment] 2024-09-26 06:09
Those 0.7 examples are awesome and get me all excited!
