### ISSUE TITLE
linker failure

### ISSUE THREAD

**Issue by luoxiaozero** [leptos-rs/leptos#3093] opened 2024-10-10 14:40 UTC
**Describe the bug**

Execute `cargo leptos serve` command, the error message is as follows:

```
error: linking with `rust-lld` failed: signal: 10 (SIGBUS)
...

          PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
          Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
          0  rust-lld                 0x0000000104a1e898 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
          1  rust-lld                 0x0000000104a1cb30 llvm::sys::RunSignalHandlers() + 112
          2  rust-lld                 0x0000000104a1ef44 SignalHandler(int) + 344
          3  libsystem_platform.dylib 0x000000018e3ffa24 _sigtramp + 56
          4  rust-lld                 0x0000000104d570b8 lld::wasm::InputChunk::writeTo(unsigned char*) const + 160
          5  rust-lld                 0x0000000104d66e80 lld::wasm::CustomSection::writeTo(unsigned char*) + 760
          6  rust-lld                 0x00000001049a91b4 std::__1::__function::__func<llvm::parallelFor(unsigned long, unsigned long, llvm::function_ref<void (unsigned long)>)::$_1, std::__1::allocator<llvm::parallelFor(unsigned long, unsigned long, llvm::function_ref<void (unsigned long)>)::$_1>, void ()>::operator()() + 48
          7  rust-lld                 0x00000001049a90cc std::__1::__function::__func<llvm::parallel::TaskGroup::spawn(std::__1::function<void ()>, bool)::$_0, std::__1::allocator<llvm::parallel::TaskGroup::spawn(std::__1::function<void ()>, bool)::$_0>, void ()>::operator()() + 40
          8  rust-lld                 0x00000001049a81c8 llvm::parallel::detail::(anonymous namespace)::ThreadPoolExecutor::work(llvm::ThreadPoolStrategy, unsigned int) + 576
          9  rust-lld                 0x00000001049a7f34 void* std::__1::__thread_proxy[abi:v15006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, llvm::parallel::detail::(anonymous namespace)::ThreadPoolExecutor::ThreadPoolExecutor(llvm::ThreadPoolStrategy)::'lambda'()>>(void*) + 524
          10 libsystem_pthread.dylib  0x000000018e3d1034 _pthread_start + 136
          11 libsystem_pthread.dylib  0x000000018e3cbe3c thread_start + 8


error: could not compile `ssr_axum` (lib) due to 1 previous error
```

**Leptos Dependencies**

```toml
leptos = { version = "0.7.0-gamma2" }
```

**To Reproduce**
1. Clone https://github.com/thaw-ui/thaw
2. Open the `examples/ssr_axum` directory.
3. Execute `cargo leptos serve` command.

**Expected behavior**

**Screenshots**

**Additional context**

The demo directory has the same problem.

1. Clone https://github.com/thaw-ui/thaw
2. Open the `demo` directory.
3. Comment out `release = true` in the Trunk.toml file.
4. Execute `trunk serve` command.

**Comment by luoxiaozero** [comment] 2024-10-10 14:42
When executing `cargo leptos serve --release` or `trunk serve --release` the problem disappears.

**Comment by benwis** [comment] 2024-10-10 16:27
> When executing `cargo leptos serve --release` or `trunk serve --release` the problem disappears.

Nightly or stable or it doesn't matter?

**Comment by luoxiaozero** [comment] 2024-10-10 16:44
> Nightly or stable or it doesn't matter?

All have this problem. 

(In addition, When I deleted the Route component in [app.rs](https://github.com/thaw-ui/thaw/blob/main/demo/src/app.rs) to 8, the problem disappeared)

**Comment by gbj** [comment] 2024-10-13 23:48
I have opened a PR #3107.

This had originated in earlier exploration of how to minimize compile times. In my testing, it does seem to fix this issue; I can build and serve the demo example locally.

Could you confirm whether it fixes it for you?

**Comment by gbj** [comment] 2024-10-14 11:55
Fair enough; I can't reproduce the out-of-memory error.

**Comment by benwis** [comment] 2024-10-14 13:49
I also don't seem to be able to reproduce the out of memory part of this error, but I do get a linker error. I suspect this may be a rust thing, and am using the thaw example as a repro for them to look at

**Comment by luoxiaozero** [comment] 2024-10-14 16:10
> I also don't seem to be able to reproduce the out of memory part of this error, but I do get a linker error.

I switched to my MacBook and tried it, and now I get this linker error as well.

**Comment by gbj** [comment] 2024-10-21 00:16
So, with #3107 merged (which should help in any case),
- `cargo leptos build --release` is fine
- `cargo build --features=ssr` is fine
- Linking for WASM is broken, with an error way beyond my comprehension
- Building with any profile that has `debug = 0` is fine

Clearly debuginfo is causing problems of some kind in the WASM build that are beyond my control or understanding.

**Comment by luoxiaozero** [comment] 2024-10-27 05:26
There is good news, I found a solution.

The current demo library component structure is as follows:

```
- App
  - AccordionMdPage
    - Dome1
    - Demo2
    - ...
  - AnchorMdPage
    - Dome1
    - Dome2
    - ...
  - AutoCompleteMdPage
    - Dmoe1
    - ...
  - ...
```

When I added `into_any()` to the Demo component, the problem disappeared. [PR](https://github.com/thaw-ui/thaw/pull/287/files) is here.

**Comment by gbj** [comment] 2024-10-27 17:36
> When I added `into_any()` to the MdPage component, the problem disappeared. [PR](https://github.com/thaw-ui/thaw/pull/287/files) is here.

Oh, that's great. We are planning to use the "component erasure" approach in cargo-leptos by default in debug builds. Good to know `.into_any()` here fixed it.

**Closed by gbj** 2024-10-27 17:36 UTC
