### ISSUE TITLE
Recursive effects never run after recursing

### ISSUE THREAD

**Issue by Giovanni-Tably** [leptos-rs/leptos#2569] opened 2024-04-29 15:19 UTC
**Describe the bug**

Effects that are recursively triggered (set signals they transitively depend on) stop reacting after recursing.
That is, the recursion is prevented somehow, and afterward the effect loses the reactive links to the signals it subscribes to and never runs again.

Also relevant:
- Recursive effects are iffy and best avoided. `:D`
- The context this came up in was an effect resetting a signal it depended on, which is not great but also a simple and obvious way to implement the intended behaviour.
- This can be fixed:
  - with `set_untracked` to break the recursion, but only if that effect is the only subscriber, or
  - by setting the signal in a separate execution context with something like `queue_microtask`. Internally we use a `defer_with` function you can see [here](https://github.com/leptos-rs/leptos/discussions/2442#discussioncomment-8829778). Note that we use the parent scope and not `defer` because the issue seemed to persist without it.

**Leptos Dependencies**

Tested in the `leptos` repo on 8686d5aabbd9720ba121fddd1fb8f5473559b670.

**To Reproduce**

Copy the following test in `leptos_reactive/tests/effect.rs` then run:
```sh
cd leptos_reactive
cargo test recursive_effect -- --nocapture
```

```rust
#[test]
fn recursive_effect() {
    use leptos::{SignalGet, SignalGetUntracked, SignalSet};

    let _runtime = create_runtime();

    let s = leptos::create_rw_signal(0);

    leptos::create_isomorphic_effect(move |_| {
        let a = s.get();
        print!("{a}");
        if a == 0 {
            return;
        }
        s.set(0);
    });

    s.set(1);
    s.set(2);
    s.set(3);

    assert_eq!(3, s.get_untracked()); // Passes

    // Current output `01`
}
```

**Expected behavior**

I expected the test to print `0123` (if recursion is prevented) or maybe `0102030`(if recursion is allowed and is up to the user to manage it). The current output is `01`.

**Comment by gbj** [comment] 2024-05-06 18:17
I looked into this a bit and I can write up a longer explanation if you'd really like to know; the short version is that it effects are marked "clean" when they finish running, so marking it dirty while it's still dirty doesn't work as you expect (because it then marks itself clean).

I'm struggling to come up with a reason this would be a good idea, though -- could you share a use case?

**Comment by luxalpa** [comment] 2024-05-23 19:23
You can somewhat workaround this issue by setting the signal from within a call to `queue_microtask`

**Comment by gbj** [comment] 2024-08-16 20:14
This logs `0102030` on 0.7, i.e., your expected result if recursion is allowed and is up to the user to manage it. I've added a regression test and will close this issue.

**Closed by gbj** 2024-08-16 20:14 UTC
