### ISSUE TITLE
Attribute spreading does not work with self closing elements in `view!` macro

### ISSUE THREAD

**Issue by tqwewe** [leptos-rs/leptos#1934] opened 2023-10-24 08:41 UTC
**Describe the bug**
Spreading attributes on a self closing tag (such as img or input) doesn't work in the `view!` macro.

For it to fail, the following must be true:
- Its a self closing tag
- It has normal attributes before the attribute spread
- The attribute spread must be after all the other attributes

Of course this means a simple work around is to put your attribute spread before other attributes.

For example, this fails:
```rust
view! {
    <img src=img_src {..attrs} />
}
```
However, this works:
```rust
view! {
    <img {..attrs} src=img_src />
}
```
Interestingly too, if `src` is a literal string instead of an ident, then it works:
```rust
view! {
    <img src="..." {..attrs} />
}
```

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

For example:
```toml
leptos = { version = "0.5.1", features = ["nightly"] }
leptos_axum = { version = "0.5.1" }
leptos_meta = { version = "0.5.1", features = ["nightly"] }
leptos_router = { version = "0.5.1", features = ["nightly"] }
leptos_dom = { version = "0.5.1", features = ["nightly"] }
```

**To Reproduce**
Create the following component:
```rust
use leptos::*;

#[component]
pub fn Img(
    #[prop(attrs)] attrs: Vec<(&'static str, Attribute)>,
) -> impl IntoView {
    let img_url = "...";

    view! { <img src=img_url {..attrs}/> }
}
```

**Expected behavior**
It should compile fine.

**Screenshots**
-

**Additional context**
-

**Comment by gbj** [comment] 2023-11-10 20:12
I *think* this might actually be an unfixable parser ambiguity.

Note the error here
```
expected struct, variant or union type, found local variable `img_url`
```
I **believe** that what's happening is that
```
<img src=img_url {..attrs}/>
```
is being interpreted as if
```rust
img_url {..attrs}
```
is a struct.

If you clarify by putting braces around `{img_url}`
```
<img src={img_url} {..attrs}/>
```
it's clear to the parser that `{img_url}` as an expression is the complete value of `src`. 

This is kind of like the rare examples that require `{ }` around `on:` handlers, depending on the syntax of the handler.

This is *definitely* not fixable in Leptos, as I have reproduced the same thing in rstml. I'm not sure if it would even be possible to fix there, or if it's a deeper syn thing. So this may be a "won't fix, but here's the workaround"

**Comment by gbj** [comment] 2023-11-15 19:48
Having thought more about this in the shower yesterday (lol) I think it's a "can't fix" because, if you're trying to parse a Rust expression, `IDENT {` is always going to look like it's a struct invocation. We usually get away without needing to wrap things in `{ ... }` but this is a case where wrapping `{img_url}` is necessary to disambiguate when parsing.

**Closed by gbj** 2023-11-15 19:48 UTC
Labels: bug

**Comment by tqwewe** [comment] 2023-11-16 03:13
Makes sense, thanks legend!
