### ISSUE TITLE
RFC: Support for Svelte-like style scoping?

### ISSUE THREAD

**Issue by bluenote10** [leptos-rs/leptos#875] opened 2023-04-16 13:03 UTC
I'm wondering if it would be possible to support Svelte-like style scoping.

# Motivation / prior art

In Svelte each component gets its own unique CSS class, and all HTML elements produced by this component get styled implicitly with that CSS class. Internally Svelte relies on using combined selectors, which dramatically reduces the number of CSS classes that need to be written explicitly.

An example: Consider this two component example:

**`Parent.svelte`**

```svelte
<script lang="ts">
  import Child from "./Child.svelte";
</script>

<p>This is a paragraph in the parent.</p>

<div>This is a div in the parent.</div>

<ul>
  <li class:selected={false}>Item 1</li>
  <li class:selected={true}>Item 2</li>
  <li class:selected={false}>Item 3</li>
</ul>

<Child>
  <p>This paragraph comes from the parent, and accordingly is styled according to parent styles.</p>
</Child>

<Child>
  <p>This paragraph comes from the parent, and accordingly is styled according to parent styles.</p>
</Child>

<style>
  p {
    color: darkblue;
  }

  div {
    border: 1px solid darkblue;
  }

  ul {
    margin: 16px;
  }

  li {
    border: 1px solid green;
  }

  .selected {
    background-color: lightblue;
  }
</style>
```

**`Child.svelte`**

```svelte
<script lang="ts">
  let selected = false;
</script>

<div class:selected>
  <p>This is a paragraph in the child.</p>

  <slot />

  <p>Selected: {selected}</p>

  <button on:click={() => (selected = !selected)}>Toggle</button>
</div>

<style>
  p {
    color: seagreen;
  }

  div {
    border: 1px solid seagreen;
  }

  .selected {
    background-color: lightgreen;
  }
</style>
```

This produces an (ugly, but styled) output like this (or check it out on the [REPL](https://svelte.dev/repl/df8a30f197be41659acc86189afcb55f?version=3.58.0)):

![image](https://user-images.githubusercontent.com/3620703/232308856-3b80aff0-4a5d-4687-93cd-c5c05dc09068.png)

Note that there is a lot going on in terms of styling without having to manually deal with lots of explicit CSS class names. Notice that the view code is **not littered by excessive CSS class referencing**. In Svelte it is in many cases sufficient to use plain element selectors to style the elements created by a component, combined with a few mixing classes like `selected`, `active`, or `deactivated`. For more motivation why Svelte went for this approach see Rich Harris' post [The zen of Just Writing CSS](https://svelte.dev/blog/the-zen-of-just-writing-css).

# Under the hood

The approach by Svelte works, because internally the selectors defined in the `<style>` section get scoped by a unique class. In the example above, Svelte creates CSS like this (the `.s-azXUKLSuEAYX` corresponds to the parent, the `.s-fVHJuYNM6LRl` to the child):

```css
p.s-azXUKLSuEAYX {
  color: darkblue;
}
div.s-azXUKLSuEAYX {
  border: 1px solid darkblue;
}
ul.s-azXUKLSuEAYX {
  margin: 16px;
}
li.s-azXUKLSuEAYX {
  border: 1px solid green;
}
.selected.s-azXUKLSuEAYX {
  background-color: lightblue;
}

p.s-fVHJuYNM6LRl {
  color: seagreen;
}
div.s-fVHJuYNM6LRl {
  border: 1px solid seagreen;
}
.selected.s-fVHJuYNM6LRl {
  background-color: lightgreen;
}
```

The DOM elements all get prefixed implicitly by the corresponding classes, i.e., the DOM looks like this:

![image](https://user-images.githubusercontent.com/3620703/232308818-191248da-501b-4411-a3f1-98ebc04a0a0c.png)

# Translation to Leptos

I'd assume the standard approach in Leptos would be to use explicit CSS classes for everything. This works, but is tedious, i.e., leads to CSS class littering: In the example above we would have a total of 8 classes that we somehow would need to sync between the view code and the CSS class name constants: We could for instance use `stylist-rs` to create 8 class name constants that get passed explicitly to all the elements (`STYLE_PARENT_P`, `STYLE_PARENT_DIV`, `STYLE_PARENT_SELECTED`, and so on). From a clean code perspective the explicit nature of that solution is ideal, but from a practical perspective it just causes so much boilerplate, and Svelte's slightly less explicit coupling can simply be a significant productivity boost.

In general I would consider the problem of creating the CSS classes a problem that can be solved outside of Leptos. So for the scope of this issue, let's assume we simply have created the necessary CSS scope classes somehow externally.

To emulate Svelte's behavior it is currently necessary to pass the corresponding CSS class **explicitly into any element created by that class**. The Leptos equivalent of the Svelte example would look something like this:

```rust
use leptos::*;

#[component]
pub fn Parent(cx: Scope) -> impl IntoView {
    view! {
        cx,
        <>
            <p class=STYLE_PARENT>"This is a paragraph in the parent."</p>
            <div class=STYLE_PARENT>"This is a div in the parent."</div>

            <ul class=STYLE_PARENT>
                <li class=STYLE_PARENT>"Item 1"</li>
                <li class={format!("{} selected", STYLE_PARENT)}>"Item 2"</li>
                <li class=STYLE_PARENT>"Item 3"</li>
            </ul>

            <Child>
                <p class=STYLE_PARENT>"This paragraph comes from the parent, and accordingly is styled according to parent styles."</p>
            </Child>

            <Child>
                <p class=STYLE_PARENT>"This paragraph comes from the parent, and accordingly is styled according to parent styles."</p>
            </Child>
        </>
    }
}

#[component]
pub fn Child(cx: Scope, children: Children) -> impl IntoView {
    let (selected, set_selected) = create_signal(cx, false);

    view! {
        cx,
        <div class=move || if selected() { format!("{} selected", STYLE_CHILD) } else { STYLE_CHILD.into() }>
            <p class=STYLE_CHILD>"This is a paragraph in the child."</p>

            {children(cx)}

            <p class=STYLE_CHILD>"Selected: " {selected}</p>

            <button class=STYLE_CHILD on:click=move |_| set_selected.update(|v| *v = !*v)>"Toggle"</button>
        </div>
    }
}

// Let's ignore where these CSS names actually come from. That's a separate problem.
const STYLE_PARENT: &str = "s-azXUKLSuEAYX";
const STYLE_CHILD: &str = "s-fVHJuYNM6LRl";
```

Note that:
- Forgetting to pass a CSS class to an element is an obvious issue.
- Appending custom classes to the "scope class" is manual and a bit tedious.

# Possible solution?

From a user perspective it would be great being able to write:

```rust
#[component(css_scope_class=STYLE_PARENT)]
pub fn Parent(cx: Scope) -> impl IntoView {
    view! {
        cx,
        <>
            <p>"This is a paragraph in the parent."</p>
            <div>"This is a div in the parent."</div>

            <ul>
                <li>"Item 1"</li>
                <li class:selected>"Item 2"</li>
                <li>"Item 3"</li>
            </ul>

            <Child>
                <p>"This paragraph comes from the parent, and accordingly is styled according to parent styles."</p>
            </Child>

            <Child>
                <p>"This paragraph comes from the parent, and accordingly is styled according to parent styles."</p>
            </Child>
        </>
    }
}

#[component(css_scope_class=STYLE_CHILD)]
pub fn Child(cx: Scope, children: Children) -> impl IntoView {
    let (selected, set_selected) = create_signal(cx, false);

    view! {
        cx,
        <div class:selected>
            <p>"This is a paragraph in the child."</p>

            {children(cx)}

            <p>"Selected: " {selected}</p>

            <button on:click=move |_| set_selected.update(|v| *v = !*v)>"Toggle"</button>
        </div>
    }
}
```

Some thoughts:

- Can the problem be solved in the `view!` macro level? Solving the problem on the `view!` macro level is probably not ideal, because a component may contain several/nested calls to `view!` and then it would again be necessary to pass around the class name multiple times. Since the goal is to scope the style on component level, it sounds more like a responsibility of the `component` macro level.
- Can the problem be solved in the `component` macro level? The example above suggest so, because the transformation is purely local on the AST level. However, as soon as the component calls helper functions to generate HTML elements (not other components!) they would have to get transformed as well.
- The above thoughts suggest that perhaps `cx: Scope` is the only place to solve the problem? Perhaps somehow if a call to e.g. `div(cx)` can check that it is happening within a component with a (non-none) `css_scope_class`, it could apply the class name? I've no idea if this could work at all, and it could definitely get tricky around `children` and `render_props` which would need to switch the styling context back to the parent, even though in terms of the DOM hierarchy they are descendants of another component.

I guess I don't have sufficient understanding of the leptos internals to really suggest anything meaningful. Would there be any hope to support that kind of CSS class scoping?

**Comment by bluenote10** [comment] 2023-04-16 13:28
Good to see some activity on this already!

But as explained, solving it on the `view!` level feels a bit error prone. When a component contains many nested `view!` fragments e.g. as a result of complex control flow or iteration, one could easily forget to forward the css scope class into every `view!` call, leading to style bugs. I was hoping this could be solved in a DRY-fashion on the component level itself.

**Comment by gbj** [comment] 2023-04-16 16:23
Sorry if I closed this too abruptly! I think that the feature described here is already available, but I'm happy to reopen if you think more discussion would be useful. I also see that my thinking in applying this at the `view` level was not explained in discussion in the linked issue, so I'll lay it out here. I'll actually talking about the three levels at which it could be handled in reverse order from the way you listed them, just for the sake of explanation:

> perhaps `cx: Scope` is the only place to solve the problem? Perhaps somehow if a call to e.g. `div(cx)` can check that it is happening within a component with a (non-none) `css_scope_class`, it could apply the class name? I've no idea if this could work at all, and it could definitely get tricky around `children` and `render_props` which would need to switch the styling context back to the parent, even though in terms of the DOM hierarchy they are descendants of another component.

This is possible, but not ideal. The problem is that it involves an additional runtime check on the creation of every single element, which introduces a pretty significant drag on performance, whether a user is actually using scoped CSS or not. It would also be fairly difficult to implement in a way that a) correctly passes the class to all of the `view` invocations within a given component, even if they are in child scopes (for example, a `<Show/>` or `<For/>` component creates a new scope for its children) without b) bleeding through to components that *don't* have a scoped style. I can imagine ways of inserting the information that would be necessary to get this to work, but they all have a runtime cost.

>  Can the problem be solved in the `component` macro level? The example above suggest so, because the transformation is purely local on the AST level. However, as soon as the component calls helper functions to generate HTML elements (not other components!) they would have to get transformed as well.

The component macro doesn't currently do anything to transform the body of the component function: it sets up the types needed for props and so on, and wraps the component function to provide some debugging information, but it doesn't walk over the body of the component function itself. The fact that `#[component]` and `view` are two separate macros means that we can't really share information between them. The `view` macro doesn't know if or that it's inside a `#[component]`, which is why the class name (or value) is passed into it. In Svelte this isn't an issue because Svelte is its own language, and the compiler *does* handle the entire component file at once, so the view does know whether there is a style declaration. 

I don't think it would be a good idea to merge the two macros and have the component macro do all the work that the view macro is currently doing, when within the body of the component function.

>     * Can the problem be solved in the `view!` macro level? Solving the problem on the `view!` macro level is probably not ideal, because a component may contain several/nested calls to `view!` and then it would again be necessary to pass around the class name multiple times. Since the goal is to scope the style on component level, it sounds more like a responsibility of the `component` macro level.

Hopefully this clarifies why this is passed into the view currently. The scoped class is basically a concern of the view function -- i.e., whether there is a scoped class or not is something that the view always need to know about, but nothing else necessarily does, so it seems reasonable to me that it's passed in as an argument. 

As far as I can tell, of the three options this is the only one that respects macro hygiene (the separation between the component and view macros) and doesn't add a runtime cost. I'm open to other ideas if you or others have them.

**Closed** 2023-05-05 18:07 UTC
Labels: feedback wanted
