### ISSUE TITLE
`<ErrorBoundary/>` not rendering in release mode

### ISSUE THREAD

**Issue by moschroe** [leptos-rs/leptos#820] opened 2023-04-06 21:07 UTC
Taking careful first steps and trying to build a little UI for parts of a custom REST API. I got a button set up to execute a `ServerFn` and get a view to update with the fetched content (or the error).

But as soon as I use `--release` on `cargo leptos watch`, the view will no longer render (though the error message will).

All that is added to the DOM is two lines of `<!---->`

I could reduce the problem to the presence of `<ErrorBoundary>`, without, the view renders for an `Ok(_)`.

I tried `cargo upgrade` and it pulled dependencies up to leptos 0.2.5 but the error persists.

**Comment by gbj** [comment] 2023-04-06 21:37
Could you please share a code example or reproduction? Thanks.

**Comment by moschroe** [comment] 2023-04-07 11:17
I cleaned up my POC a little, it is a clunky mess of starter template and tutorial code, slightly adapted for experimentation, see here: https://github.com/moschroe/leptos-testbed

**Comment by gbj** [comment] 2023-04-07 14:25
Thanks, I'm able to reproduce it and it does indeed seem to be an issue with `<ErrorBoundary/>` in release mode. I'll try to take a crack at solving it in the next couple weeks.

**Comment by gbj** [comment] 2023-04-14 20:12
... I honestly don't know what I did that fixed this since last week, but when I went back to reproduce I was unable to reproduce it on the latest `main`. I'm going to close this for now but feel free to ping me and I'll reopen it if you'll still having trouble.

https://user-images.githubusercontent.com/286622/232145813-eeda44a4-6fa4-4378-ac83-2967f6367c17.mov

**Comment by moschroe** [comment] 2023-04-21 18:17
I found time to test this, sadly it was the same for me.

I changed the dependencies in `Cargo.toml` to `git="https://github.com/leptos-rs/leptos", branch="main"` (initially tried 90972f2d9454b4be1be40113058c3c9c8dc2e1be from around the time you commented last)  and still observed the empty comments being added.

I made sure Firefox in dev mode would not cache stuff and I cleared the target directory, building everything new.

**Comment by gbj** [comment] 2023-04-21 18:34
Did you run `cargo update` after switching to the git dependency? 

Are we still looking at the home page of https://github.com/moschroe/leptos-testbed?

If so, I am not able to reproduce an issue when running against the latest.

**Comment by moschroe** [comment] 2023-04-23 10:31
I tried to find a small set of changes to reproduce and succeeded. I updated the [testbed project](https://github.com/moschroe/leptos-testbed).

Rendering works on the initial view and breaks (permanently) as soon as I navigate to the other view.

When force-reloading the tab with the path already set to `/second`, rendering immediately breaks and the following error appears on the console:

```
panicked at 'before to not err: JsValue(HierarchyRequestError: CharacterData.before: The new child is an ancestor of the parent
getImports/imports.wbg.__wbg_before_44f875c751453be4/<@http://localhost:3000/pkg/leptos_start.js:654:17
handleError@http://localhost:3000/pkg/leptos_start.js:257:38
getImports/imports.wbg.__wbg_before_44f875c751453be4@http://localhost:3000/pkg/leptos_start.js:653:65
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[744]:0x64e30
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[164]:0xda41
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[169]:0x123e8
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[536]:0x56cd5
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[247]:0x305ad
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[425]:0x4cc1b
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[164]:0xce44
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[169]:0x123e8
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[536]:0x56cd5
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[405]:0x4a573
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[348]:0x42a32
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[828]:0x6b228
__wbg_adapter_54@http://localhost:3000/pkg/leptos_start.js:238:6
real@http://localhost:3000/pkg/leptos_start.js:207:32
promise callback*getImports/imports.wbg.__wbg_then_ec5db6d509eb475f@http://localhost:3000/pkg/leptos_start.js:976:29
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[884]:0x6be02
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[466]:0x52097
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[493]:0x5456d
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[408]:0x4aa25
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[711]:0x638ac
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[828]:0x6b228
__wbg_adapter_54@http://localhost:3000/pkg/leptos_start.js:238:6
real@http://localhost:3000/pkg/leptos_start.js:207:32
promise callback*getImports/imports.wbg.__wbg_then_f753623316e2873a@http://localhost:3000/pkg/leptos_start.js:980:29
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[267]:0x3480b
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[369]:0x45758
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[162]:0x81c7
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[405]:0x49d4a
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[348]:0x42a32
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[828]:0x6b228
__wbg_adapter_54@http://localhost:3000/pkg/leptos_start.js:238:6
real@http://localhost:3000/pkg/leptos_start.js:207:32
)', /home/moe/.cargo/git/checkouts/leptos-2c8932a5258b3db6/9a4f3ab/leptos_dom/src/components/dyn_child.rs:285:33

Stack:

getImports/imports.wbg.__wbg_new_abda76e883ba8a5f@http://localhost:3000/pkg/leptos_start.js:322:13
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[968]:0x6d2fc
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[507]:0x5518e
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[754]:0x68d1d
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[592]:0x5a7df
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[164]:0xda83
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[169]:0x123e8
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[536]:0x56cd5
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[247]:0x305ad
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[425]:0x4cc1b
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[164]:0xce44
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[169]:0x123e8
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[536]:0x56cd5
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[405]:0x4a573
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[348]:0x42a32
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[828]:0x6b228
__wbg_adapter_54@http://localhost:3000/pkg/leptos_start.js:238:6
real@http://localhost:3000/pkg/leptos_start.js:207:32
promise callback*getImports/imports.wbg.__wbg_then_ec5db6d509eb475f@http://localhost:3000/pkg/leptos_start.js:976:29
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[884]:0x6be02
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[466]:0x52097
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[493]:0x5456d
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[408]:0x4aa25
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[711]:0x638ac
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[828]:0x6b228
__wbg_adapter_54@http://localhost:3000/pkg/leptos_start.js:238:6
real@http://localhost:3000/pkg/leptos_start.js:207:32
promise callback*getImports/imports.wbg.__wbg_then_f753623316e2873a@http://localhost:3000/pkg/leptos_start.js:980:29
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[267]:0x3480b
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[369]:0x45758
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[162]:0x81c7
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[405]:0x49d4a
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[348]:0x42a32
@http://localhost:3000/pkg/leptos_start.wasm:wasm-function[828]:0x6b228
__wbg_adapter_54@http://localhost:3000/pkg/leptos_start.js:238:6
real@http://localhost:3000/pkg/leptos_start.js:207:32


leptos_start.js:335:9
```

In non-release mode, no error occurs and everything works as intended, even navigating between views multiple times and loading the second view immediately. I hope I'm not "holding it wrong" and this helps in tracking down some wayward optimization.

PS: Just to make sure that the git version is used:
```
# cargo tree | rg leptos
leptos-testbed v0.1.0 (<PATH>/leptos-testbed)
├── leptos v0.2.5 (https://github.com/leptos-rs/leptos?branch=main#9a4f3ab0)
│   ├── leptos_config v0.2.5 (https://github.com/leptos-rs/leptos?branch=main#9a4f3ab0)
│   ├── leptos_dom v0.2.5 (https://github.com/leptos-rs/leptos?branch=main#9a4f3ab0)
│   │   ├── leptos_reactive v0.2.5 (https://github.com/leptos-rs/leptos?branch=main#9a4f3ab0)
│   ├── leptos_macro v0.2.5 (proc-macro) (https://github.com/leptos-rs/leptos?branch=main#9a4f3ab0)
│   │   ├── leptos_hot_reload v0.2.5 (https://github.com/leptos-rs/leptos?branch=main#9a4f3ab0)
│   │   ├── server_fn_macro v0.2.5 (https://github.com/leptos-rs/leptos?branch=main#9a4f3ab0)
│   ├── leptos_reactive v0.2.5 (https://github.com/leptos-rs/leptos?branch=main#9a4f3ab0) (*)
│   ├── leptos_server v0.2.5 (https://github.com/leptos-rs/leptos?branch=main#9a4f3ab0)
│   │   ├── leptos_reactive v0.2.5 (https://github.com/leptos-rs/leptos?branch=main#9a4f3ab0) (*)
│   │   ├── server_fn v0.2.5 (https://github.com/leptos-rs/leptos?branch=main#9a4f3ab0)
│   │   │   ├── server_fn_macro_default v0.2.5 (proc-macro) (https://github.com/leptos-rs/leptos?branch=main#9a4f3ab0)
│   │   │   │   ├── server_fn_macro v0.2.5 (https://github.com/leptos-rs/leptos?branch=main#9a4f3ab0) (*)
│   ├── server_fn v0.2.5 (https://github.com/leptos-rs/leptos?branch=main#9a4f3ab0) (*)
├── leptos_meta v0.2.5 (https://github.com/leptos-rs/leptos?branch=main#9a4f3ab0)
│   ├── leptos v0.2.5 (https://github.com/leptos-rs/leptos?branch=main#9a4f3ab0) (*)
├── leptos_router v0.2.5 (https://github.com/leptos-rs/leptos?branch=main#9a4f3ab0)
│   ├── leptos v0.2.5 (https://github.com/leptos-rs/leptos?branch=main#9a4f3ab0) (*)
```

**Comment by gbj** [comment] 2023-04-26 18:52
Okay here's a much more minimal reproduction of the behavior I think is actually driving this—or at least one bugged behavior I'm seeing—transitioning between two different `Ok` views is broken. (In your case, from `None` to `Some(Ok(_))`

I'll see if I can figure out what's going on.

```rust
#[component]
pub fn App(cx: Scope) -> impl IntoView {
    let (value, set_value) = create_signal(cx, Ok(0));

    let on_input = move |ev| set_value(event_target_value(&ev).parse::<i32>());
    let value_view = move || { value().map(|value| if value % 2 == 0 {
        view! { cx, <p>"Even: " {value}</p> }
    } else {
        view! { cx, <p>"Odd: " {value}</p> }
    }) };

    view! { cx,
        <h1>"Error Handling"</h1>
        <label>
            <input type="number" on:input=on_input/>
            <ErrorBoundary
                // the fallback receives a signal containing current errors
                fallback=|cx, _| view! { cx,
                    <p>"ERROR"</p>
                }
            >
                {value_view}
            </ErrorBoundary>
        </label>
    }
}
```

**Comment by gbj** [comment] 2023-04-26 19:16
Thanks, this has helped me uncover some real issues with `<ErrorBoundary/>` and for once, I feel like I'm leaving a bug report with a clearer sense of how to do things well and fix other similar issues in the future, which... is a real treat.

#957 should fix the behavior of your example, in debug or release mode.

**Closed** 2023-04-26 21:31 UTC
Labels: bug
