### ISSUE TITLE
Nested <For> does not update

### ISSUE THREAD

**Issue by Nonakesh** [leptos-rs/leptos#922] opened 2023-04-22 08:10 UTC
I encountered another problem while working on my toy project with nested game state. I'm not sure what the problem is here, but I'd guess it's some sort of caching issue in For, or I'm simply using Signals wrong?

I created a component that shows the problem, the `static` variant is what I ended up with, but it has to regenerate the whole list of categories whenever there is a change. The version using `<For>` is completely broken, it seems like it doesn't update on any changes in the nested Vec's. I've tried a few workarounds, but the only thing that actually worked in all cases was the fully static one I included as well.

```rust
use leptos::*;
use std::collections::HashMap;

#[component]
pub fn Foo(cx: Scope) -> impl IntoView {
    let raw_data = [3, 4, 5]
        .iter()
        .map(|x| create_rw_signal(cx, *x))
        .enumerate()
        .collect::<Vec<_>>();
    let (data, write_data) = create_signal(cx, raw_data);

    let categorized = move || {
        data.with(|data| {
            let mut categorized = data
                .iter()
                .fold(HashMap::new(), |mut acc, &(id, value)| {
                    acc.entry(categorize(id))
                        .or_insert_with(Vec::new)
                        .push((id, value));
                    acc
                })
                .into_iter()
                .collect::<Vec<_>>();

            // Sort everything for clarity
            categorized.sort_by_key(|(category, _)| *category);
            for (_, values) in &mut categorized {
                values.sort_by_key(|(id, _)| *id);
            }

            categorized
        })
    };

    let new_element = move |_| {
        write_data.update(|data| {
            data.push((data.len(), create_rw_signal(cx, 0)));
            log_data(data);
        })
    };

    let increment_all = move |_| {
        // It shouldn't be necessary to call update here, only the inner values get changed?
        data.with(|data| {
            for (_, value) in data {
                value.update(|value| *value += 1);
            }
            log_data(data);
        });
    };

    let static_for = move || {
        log!("Full static regeneration");
        categorized()
            .into_iter()
            .map(|(category, category_values)| {
                let values = move || {
                    category_values
                        .iter()
                        .map(|(id, value)| {
                            view! {cx,
                                <div>{format!("Id: {} Value: {}", id, value.get())}</div>
                            }
                        })
                        .collect::<Vec<_>>()
                };
                view! {cx,
                    <h2>{format!("Category: {}", category)}</h2>
                    {values}
                }
            })
            .collect::<Vec<_>>()
    };

    view! {cx,
        <h1>"Using <For>"</h1>
        <For
            each=categorized
            key=|(category, _)| *category
            view=move |cx, (category, category_values)| view! {cx,
                <h2>{format!("Category: {}", category)}</h2>
                <For
                    // I'd also like to find a way of calling this without clone
                    // The only other thing that seems to work with lifetimes is to create a signal
                    // but the categories depend only on "data" so a signal shouldn't be necessary here, right?
                    each=move || category_values.clone()
                    key=|(id,_)| *id
                    view=move |cx, (id, value)| view! {cx,
                        <div>{format!("Id: {} Value: {}", id, value.get())}</div>
                    }
                />
            }
        />
        <h1>"Static"</h1>
        {static_for}
        <h1>"Interaction"</h1>
        <button on:click=new_element>"New element"</button>
        <button on:click=increment_all>"Increment all"</button>
    }
}

fn log_data(data: &Vec<(usize, RwSignal<i32>)>) {
    log!(
        "{}",
        data.iter()
            .map(|(id, value)| format!("id: {} value: {}, ", id, value.get()))
            .collect::<String>()
    )
}

fn categorize(value: usize) -> usize {
    value % 4
}
```

**Comment by gbj** [comment] 2023-04-22 11:25
If I understand correctly in the `<For/>` version the "New element" button is working as intended, but not "Incremental all"?

The problem is that this line is not reactive:
```rust
<div>{format!("Id: {} Value: {}", id, value.get())}</div>
```
It should be
```rust
<div>{move || format!("Id: {} Value: {}", id, value.get())}</div>
```
Plain values (the `String` you get from `format!`) passed into the view do not cause reactive updates; only functions or signals passed into the view cause reactive updates, so adding a closure here causes it to correctly update the counts on "increment all".

**Comment by Nonakesh** [comment] 2023-04-23 04:26
While that does fix the increment problem (I was actually quite confused by that one, I didn't have it in my actual project), it doesn't fix the problem that categories don't get updated.

`New element` only works in the static version. In the <For> version, it only works when a new category is added, not when new elements are added to that category.

**Comment by gbj** [comment] 2023-04-26 02:28
Sorry for the slow response. This is a fairly complicated example and I haven't had much time to wrap my head around it.

I don't see any reason in your example to think that `category_values` in the inner `<For/>` would trigger reactive changes. It's just a plain `Vec`, not a signal or a derived signal. Adding new elements leads `categorized` to continue updating, but the inner `category_values` that's stored for each category is a plain `Vec` not a reactive value. What you actually want to do here is to take a reactive slice -- a derived signal or a memo -- from that reactive `categories`, rather than a non-reactive version.

Here's a rather bad version, but it achieves what you want: only making targeted, keys updates, i.e., inserting a single element rather than rerendering the whole table per change. The key difference here is the recognition that `categories` is the reactive value, and that each row is a reactive slice of it.

I'm sure you can refactor and improve this pretty significantly but I'm a little tired:
```rust
#[component]
pub fn App(cx: Scope) -> impl IntoView {
    let raw_data = [3, 4, 5]
        .iter()
        .map(|x| create_rw_signal(cx, *x))
        .enumerate()
        .collect::<Vec<_>>();
    let (data, write_data) = create_signal(cx, raw_data);

    let categorized = create_memo(cx, move |_| {
        data.with(|data| {
            let mut categorized = data
                .iter()
                .fold(HashMap::new(), |mut acc, &(id, value)| {
                    acc.entry(categorize(id))
                        .or_insert_with(Vec::new)
                        .push((id, value));
                    acc
                })
                .into_iter()
                .collect::<Vec<_>>();

            // Sort everything for clarity
            categorized.sort_by_key(|(category, _)| *category);
            for (_, values) in &mut categorized {
                values.sort_by_key(|(id, _)| *id);
                //values.update(|values| values.sort_by_key(|(id, _)| *id));
            }

            categorized
        })
    });

    let new_element = move |_| {
        write_data.update(|data| {
            data.push((data.len(), create_rw_signal(cx, 0)));
            log_data(data);
        })
    };

    let increment_all = move |_| {
        // It shouldn't be necessary to call update here, only the inner values get changed?
        data.with(|data| {
            for (_, value) in data {
                value.update(|value| *value += 1);
            }
            log_data(data);
        });
    };

    view! {cx,
        <h1>"Using <For>"</h1>
        <For
            each=categorized
            key=|(category, _)| *category
            view=move |cx, (category, category_values)| {
                // takes a memoized slice, for this category, of the original reactive `categories`
                let category_values = create_memo(cx, move |_| {
                    categorized.with(|categorized| categorized.iter().find(|(s_category, _)| *s_category == category).unwrap().1.clone())
                });
                view! {cx,
                    <h2>{format!("Category: {}", category)}</h2>
                    <For
                         each=category_values
                        key=|(id,_)| *id
                        view=move |cx, (id, value)| view! {cx,
                            <div>{move || format!("Id: {} Value: {}", id, value.get())}</div>
                        }
                    />
                }
            }
        />
        <h1>"Interaction"</h1>
        <button on:click=new_element>"New element"</button>
        <button on:click=increment_all>"Increment all"</button>
    }
}
```

I'm going to close the issue as this doesn't seem to be a bug in `<For/>` after all, but feel free to reply or find us on Discord (link in Readme) if you have any trouble with the refactor.

**Closed by gbj** 2023-04-26 02:28 UTC
Labels: support

**Comment by gbj** [comment] 2023-04-26 02:42
P.S. Just while it's still on my mind, the refactor that would make sense to me would be
A) a signal that holds a flat `Vec<_>` of all the values
B) a memo of the categories 
C) a memo (whether constructed inside the first `<For/>` or as a table of memos at the top level) of the values

But I'm sure there are several different ways to do it.

P. P. S. Thinking for the future — the `move || category_values.clone()`, which you rightly flagged in a comment, is a good sign "this will not be reactive" — a function that returns a cloned `Vec` that you've moved into it can never return a different value from the last run, so couldn't ever update the inner `<For/>`
