### ISSUE TITLE
Clicking links inside a Suspense panics

### ISSUE THREAD

**Issue by johansmitsnl** [leptos-rs/leptos#1465] opened 2023-07-29 08:55 UTC
**Describe the bug**

When you use a link in the router that is wrapped inside a `Suspense`

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

```toml
leptos = { version = "0.5.0-alpha", default-features = false, features = ["serde", "nightly"] }
leptos_router = {version = "0.5.0-alpha", default-features = false}
```

**To Reproduce**
1. Go to When you click a link
4. `panicked at 'context of type "leptos_reactive::suspense::GlobalSuspenseContext" to be present', /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_reactive-0.5.0-alpha/src/context.rs:202:9`

**Expected behavior**
Be able to click on links

**Comment by gbj** [comment] 2023-07-29 10:29
Please provide an example that reproduces this behavior, if possible. I believe you that it's happening but am not able to reproduce it in my own largeish application.

**Comment by johansmitsnl** [comment] 2023-07-29 14:42
This is sufficient for the error:

```rs
#[component]
pub(crate) fn App() -> impl IntoView {
    view! {
        <Suspense fallback=move || view! { "Loading" }>
            <Router>
                <Routes>
                    <Route path="/*any" view=move || view! {
                        <a href="#one">one</a>
                        " | "
                        <a href="#two">two</a>
                    }/>
                </Routes>
            </Router>
        </Suspense>
    }
}

fn main() {
    console_error_panic_hook::set_once();
    console_log::init_with_level(log::Level::Debug).unwrap();

    mount_to_body(|| view! { <App/> })
}
```

**Comment by gbj** [comment] 2023-07-29 15:34
Panic should be fixed on the `effect-cleanups` branch now, and the example seems to work fine. Let me know if you run into further issues with it.

**Closed by gbj** 2023-07-29 15:34 UTC
Labels: bug
