### ISSUE TITLE
Signal type conversion

### ISSUE THREAD

**Issue by luoxiaozero** [leptos-rs/leptos#3200] opened 2024-11-06 05:51 UTC
**Describe the bug**

If the component parameter is of type Signal\<T\>, [impl\<T\> From\<T\> for Signal\<T\>](https://github.com/leptos-rs/leptos/blob/5cc2f3858dbd9307c6c630f5f25172511bc8c036/reactive_graph/src/wrappers.rs#L616) and [impl\<T\> From\<T\> for Signal\<Option\<T\>\>](https://github.com/leptos-rs/leptos/blob/5cc2f3858dbd9307c6c630f5f25172511bc8c036/reactive_graph/src/wrappers.rs#L859) will conflict. 

```
error[E0283]: type annotations needed
  --> src/main.rs:5:9
   |
5  |         view! { <SimpleCounter step=1 /> }
   |         ^^^^^^^^^^^^^^^^^^^^^^^----^^^^^^^
   |         |                      |
   |         |                      required by a bound introduced by this call
   |         cannot infer type for struct `leptos::prelude::Signal<_>`
   |
   = note: multiple `impl`s satisfying `leptos::prelude::Signal<_>: From<i32>` found in the `reactive_graph` crate:
           - impl<T> From<T> for leptos::prelude::Signal<T>
             where T: Send, T: std::marker::Sync, T: 'static;
           - impl<T> From<T> for leptos::prelude::Signal<std::option::Option<T>>
             where T: Send, T: std::marker::Sync, T: 'static;
   = note: required for `i32` to implement `Into<leptos::prelude::Signal<_>>`
```

**Leptos Dependencies**

leptos-v0.7.0-rc1

**To Reproduce**
Run the following code:
```rust
use leptos::prelude::*;

pub fn main() {
    mount_to_body(|| {
        view! { <SimpleCounter step=1 /> }
    })
}

#[component]
pub fn SimpleCounter<T>(#[prop(into)] step: Signal<T>) -> impl IntoView
where
    T: Send + Sync + 'static,
{
    view! {<div></div>}
}
```

**Expected behavior**

Delete `impl<T> From<T> for Signal<Option<T>>` and keep only `impl<T> From<T> for Signal<T>`.

**Screenshots**

**Additional context**

**Comment by gbj** [comment] 2024-11-06 13:18
@zakstucke looks like this is due to #3098: adding additional implementations for `Into<Signal<T>>` breaks the compiler's ability to infer which one we're trying to use, which can't be specified in the view macro.

Do you have any thoughts on a way to work around this? Otherwise I'll need to remove some of those additional implementations before release.

**Comment by zakstucke** [comment] 2024-11-06 21:41
@gbj it's a tricky one, I actually noticed this when I PR'd: this happened in only one location across all my projects and was fixed by a tiny downstream change, I figured it would be fine. I can't see an obvious stable fix for this until specialisation or negative trait impls.

Given we're not deprecating `MaybeProp`, changing `step: Signal<T>` here to `step: MaybeProp<T>` fixes the issue entirely, and has no downsides now that `MaybeProp` is `Copy`. 

Given that, I vote no change needed, there's an easy fix (^) and the ergonomics for having the impls are really nice.

**Comment by zakstucke** [comment] 2024-11-06 22:15
Yeah I can't think of anything not overly complicated. 

This doesn't hurt as bad now we're keeping `MaybeProp`.

Unless you think of something, looks like only these will need removing:
- `impl<T> From<T> for Signal<Option<T>>`
- `impl<T> From<T> for Signal<Option<T>, LocalStorage>`

This shouldn't be an issue for any non raw `From<T>`.

**Comment by zakstucke** [comment] 2024-11-06 22:20
Actually this seems to apply to a lot, e.g. `RwSignal::new(1)` too, this would lose out on a bunch or ergonomics.

**Comment by zakstucke** [comment] 2024-11-06 22:28
Before realising that it doesn't just apply to `Option<T>` impls, but basically any custom `impl` for signals, given they implement `impl<T> From<T> for leptos::prelude::Signal<T>`, it seems this pattern is the problem and a different pattern's needed for generics, rather than removing ergonomics from `Signal`.

**Comment by luoxiaozero** [comment] 2024-11-07 01:46
> Given we're not deprecating MaybeProp, changing step: Signal<T> here to step: MaybeProp<T> fixes the issue entirely, and has no downsides now that MaybeProp is Copy.

My original intention of using `Signal` is that the user must provide a value.  If it is changed to `MaybeProp` type, then I must handle the case of `None` wherever `MaybeProp` is used.

**Comment by gbj** [comment] 2024-11-17 21:05
Looking back at this again: Right, @zakstucke is right, the issue is that if we `impl<T> From<T> for Signal<T>`, then the compiler can't infer whether you mean that you want `Signal<i32>` or `Signal<RwSignal<i32>>` if you just pass it `step=42`. 

`Signal<RwSignal<i32>>` is a useless type that you would never want, but the compiler doesn't know that.

0.6 doesn't `impl<T> From<T> for Signal<T>` and so my inclination would simply be to remove this implementation.

**Comment by gbj** [comment] 2024-11-17 21:32
NB the actual culprit here is the `impl<T> From<T> for Signal<T>`, which I added a few months before #3098, but similar issues arise with inference for others. I've tried to remove the possible issues with #3255.

**Closed** 2024-11-18 16:03 UTC
Labels: bug
