### ISSUE TITLE
My short onboarding experience

### ISSUE THREAD

**Issue by adsick** [leptos-rs/leptos#2141] opened 2023-12-29 16:55 UTC
Hi there, I'm trying to get into web development with Leptos but experience some rough edges with this repo in particular:

* My 1st problem is that the examples are excluded from the root Cargo workspace, which makes it harder to explore them in my text editor (VS Code) because rust analyzer can't work on excluded packages (I know that this topic was brought up here and there, but I don't quite get what the outcome is)
* running examples with `cargo-make` my experience was a little rough because
1) I didn't switch rust to nightly, there is a nightly note in the toplevel readme, but in the readme in `examples` there are no notes that you should switch to nightly to run the examples
2) When you `cd` into some example `A` and perform `rustup override set nightly` everything is fine, but then you wanna check out other example, you `cd` there and now rust is set to stable again => you are confused.
for it to work normally you either need to cd to root of the repo and do a `rustup override set nightly` there, or set nightly as the default which I don't wanna do. Another option is to add a `rustuptoolchain.toml` which this repo does not for some reason, there is a PR: #1979 for that I guess.
* restarting/stopping examples: main examples readme says how to _run_ examples, but not how to _stop_ them. I had to explore `examples/cargomake/process.toml` to see a stop task there, I think that the examples readme has to teach not only how to start things but also how to stop them.

P.S. onboarding matters, [the book](https://book.leptos.dev/) is great but that is more about the theory. The repo is more about practice (imo).

**Comment by adsick** [comment] 2023-12-29 17:03
opting out of workspaces also include this issues: 
* heavy total examples size
* longer compile times
when packages are in a workspace they share same compiled libraries so there is no need to recompile them every time and they don't use extra space on disk.

**Comment by adsick** [comment] 2023-12-29 17:09
is it just me or `cargo make` in the root of the repo causes it to test everything in circles? I see the same `running 46 tests` (*output*) over and over again.

**Comment by benwis** [comment] 2023-12-30 02:26
Appreciate the feedback, let's take a look at some of this
1. I would not recommend using `cargo make`, instead I would use either the standard `cargo leptos watch` command or trunk, depending on the example. Our README IMO should not recommend that. I'll talk with the team
2. This one depends on how you configure your rust. If you're using rustup, you can do `rustup default nightly`, and then you won't have to do that. Alternatively, the PR you mentioned is for a different nix issue

**Comment by gbj** [comment] 2023-12-30 13:13
Re: having the examples in a workspace — I know we've gone back and forth on this several times. It's currently set up hte way it is because the `cargo-leptos` tool is designed for the use case of people's actual apps, not the use case of having 20 unrelated examples in a repo. So for example, if I add `examples/todo_app_sqlite` to the root `Cargo.toml` workspace members, and then use `cargo leptos watch` from `examples/todo_app_sqlite`, it compiles and then panics because it can't find `Todos.db`. This is because the binary is now located in `target` in the *root* of the repo, not in the example directory where I'm running it, etc., so the relative path is wrong. The same thing may well be true for the static file serving setups, etc. I'm sure this could all be fixed (PR welcome) but each of the examples is written to be a standalone project that can be pulled out of the repo and used on its own, so any fix would have to be compatible with that.

Re: running/stopping the examples — thanks for the feedback. I'll clarify the `examples` README to add info about `cargo make stop`, and also to clarify that using `cargo make` is *not* a necessary part of running the examples or of using Leptos, which is a confusion I've seen elsewhere. I guess we could add `rust-toolchain.toml` files too — I'll create a separate issue for that.

**Comment by JosiahParry** [comment] 2023-12-30 15:14
Thanks for making this issue! I'm having a fairly similar experience (though less with `cargo-make`). I figured I may as well tag in here for an additional users experience (albeit i'm not a web-dev but data-science fella). 

The last point in the post-script you mentioned I think is very important. I'm trying to rely on the book as it's the only source of documentation I've been able to find (an unfortunate dearth of blog posts etc). It mentions very briefly some concepts that are obviously very important! But then does not illustrate _how_ to implement them in some minimal examples. Chapter 3 where it walks through progressively improving the counter example was very helpful. I found it to be the most applicable. From thereon, though, the content cannot be reproduced on my end. 

The jump from the book to the examples is very tough! The examples are workspaced, so they can't be plucked out, and they can't be created as a template using cargo leptos because of the mono-repo structure. And lastly, the examples have Cargo.toml files that are 100+ lines long! That alone is a lot to try and take i.t 

All that said, this is a really great tool and I'm enjoying being able to use it. It's just the uptake is very slow and tough!

**Comment by gbj** [comment] 2023-12-30 15:36
>  From thereon, though, the content cannot be reproduced on my end.

@JosiahParry I'm a little confused by this part: Up through Chapter 9 (the router), almost every subsection ends with a CodeSandbox with a complete, working example illustrating the concepts. What do you mean by the content not being reproducible?

> The jump from the book to the examples is very tough! The examples are workspaced, so they can't be plucked out, and they can't be created as a template using cargo leptos because of the mono-repo structure.

I'd suggest git cloning the repo and then `cp` or copy and pasting any of the example directories and mess around with them.

**Comment by benwis** [comment] 2023-12-30 17:20
> Thanks for making this issue! I'm having a fairly similar experience (though less with `cargo-make`). I figured I may as well tag in here for an additional users experience (albeit i'm not a web-dev but data-science fella).
> 
> The last point in the post-script you mentioned I think is very important. I'm trying to rely on the book as it's the only source of documentation I've been able to find (an unfortunate dearth of blog posts etc). It mentions very briefly some concepts that are obviously very important! But then does not illustrate _how_ to implement them in some minimal examples. Chapter 3 where it walks through progressively improving the counter example was very helpful. I found it to be the most applicable. From thereon, though, the content cannot be reproduced on my end.
> 
> The jump from the book to the examples is very tough! The examples are workspaced, so they can't be plucked out, and they can't be created as a template using cargo leptos because of the mono-repo structure. And lastly, the examples have Cargo.toml files that are 100+ lines long! That alone is a lot to try and take i.t
> 
> All that said, this is a really great tool and I'm enjoying being able to use it. It's just the uptake is very slow and tough!

If you're getting stuck in the book, feel free to ask for help in our Discord, or create a different issue with specifics. We'd love to hear what specifically you're having issues with, so that our book writers can get good back

**Comment by gbj** [comment] 2024-01-13 13:39
I've added simpler, non `cargo-make` instructions back to the examples and we've added toolchain files for all the examples, so I'm going to close this issue now as I don't think there's further concrete action to take.

**Closed by gbj** 2024-01-13 13:39 UTC

**Comment by sagiegurari** [comment] 2024-01-16 06:19
just saw this one and understood the toolchain setup (nightly) is difficult and confusing.
just a small pointer, you can define the toolchain for a specific task/s in the makefile:
https://github.com/sagiegurari/cargo-make?tab=readme-ov-file#usage-toolchain
for example:

```toml
[tasks.rustc-version-nightly]
toolchain = "nightly"
command = "rustc"
args = [ "--version" ]
```

it will set it up for you and reduce the confusion for users.
