### ISSUE TITLE
Login with API token (CSR only) example fails when trying to register user

### ISSUE THREAD

**Issue by kevinold** [leptos-rs/leptos#1833] opened 2023-10-03 02:00 UTC
**Describe the bug**
When running `examples/login_with_token_csr_only` on master added in #523 I receive an error

> SerdeError(Error("EOF while parsing a value", line: 1, column: 0))

**Leptos Dependencies**

**To Reproduce**
1. Clone leptos repo
2. cd examples/login_with_token_csr_only
3. cargo build
4. cargo install cargo-make
5. cargo make start
6. Navigate to http://0.0.0.0:8080/register in a browser
7. Populate email with "user@example.com" (or any email) and password with a password
8. Observe error in screenshot

**Expected behavior**
A user is registered when the form is submitted

**Screenshots**
<img width="1438" alt="Screenshot 2023-10-02 at 8 57 58 PM" src="https://github.com/leptos-rs/leptos/assets/21967/ee36d3e8-27b7-4d9f-8b79-667f7b8e182d">

**Additional context**
The same issue happens for the login form.

The issue happens here: https://github.com/leptos-rs/leptos/blob/main/examples/login_with_token_csr_only/client/src/api.rs#L24

I tried to debug with a lot message to see what was in credentials, but can't get it to display.  I fiddled with the compiler feedback, but couldn't get anywhere.

<img width="1051" alt="Screenshot 2023-10-02 at 9 11 25 PM" src="https://github.com/leptos-rs/leptos/assets/21967/178dbe2a-c80a-48d8-8fb9-be14632b60e2">

FYI, I'm new to Rust and all of my debugging skills are exhausted at this point, but I want to understand how to debug and/or arrive at the fix.  Thanks

cc @flosse who added the example

**Comment by flosse** [comment] 2023-10-03 02:34
@kevinold thanks for reporting this issue. I'll have closer look soon.

**Comment by kevinold** [comment] 2023-10-03 02:38
@flosse Very welcome.  Related to this example, I've submitted #1834 which resolves it as best I know how.

**Comment by gbj** [comment] 2023-10-07 11:38
I'm not able to reproduce this error.

**Comment by kevinold** [comment] 2023-10-13 15:51
This is so strange.  I'm following the instructions in the `examples/README` to install the nightly version of Rust and it's dependencies.

I run:

```
$ rustup toolchain install nightly
$ rustup target add wasm32-unknown-unknown
$ rustup default nightly
info: using existing install for 'nightly-aarch64-apple-darwin'
info: default toolchain set to 'nightly-aarch64-apple-darwin'

  nightly-aarch64-apple-darwin unchanged - rustc 1.75.0-nightly (e20cb7702 2023-10-12)

```


When I run `cargo make start` this is the output I receive now:

```
➜  login_with_token_csr_only git:(main) ✗ cm start
[cargo-make] INFO - cargo make 0.37.2
[cargo-make] INFO - Calling cargo metadata to extract project info
[cargo-make] INFO - Cargo metadata done
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: start
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Running Task: workspace
/Users/kevin/github_clones/leptos/examples/login_with_token_csr_only
[cargo-make][1] INFO - Calling cargo metadata to extract project info
[cargo-make][1] INFO - Cargo metadata done
[cargo-make][1] INFO - Project: client
[cargo-make][1] INFO - Build File: Makefile.toml
[cargo-make][1] INFO - Task: start
[cargo-make][1] INFO - Profile: development
[cargo-make][1] INFO - Skipping Task: legacy-migration
[cargo-make][1] INFO - Running Task: maybe-start-server
/var/folders/vd/1sbx_ywd60ncgn6lyhkjpqk80000gn/T/fsio_cx7egPjxCi.sh: line 6: [: too many arguments
  server is already started
[cargo-make][1] INFO - Running Task: maybe-start-client
  Starting trunk
[cargo-make][1] INFO - Build Done in 0.46 seconds.
[cargo-make][1] INFO - Calling cargo metadata to extract project info
[cargo-make][2] INFO - Calling cargo metadata to extract project info
[cargo-make][2] INFO - Cargo metadata done
[cargo-make][1] INFO - Cargo metadata done
[cargo-make][2] INFO - Project: client
[cargo-make][2] INFO - Build File: Makefile.toml
[cargo-make][2] INFO - Task: start-client
[cargo-make][2] INFO - Profile: development
[cargo-make][2] INFO - Skipping Task: legacy-migration
[cargo-make][2] INFO - Execute Command: "trunk" "serve"
2023-10-13T15:40:18.434472Z  INFO 📦 starting build
2023-10-13T15:40:18.435118Z  INFO spawning asset pipelines
[cargo-make][1] INFO - Project: api-boundary
[cargo-make][1] INFO - Build File: Makefile.toml
[cargo-make][1] INFO - Task: start
[cargo-make][1] INFO - Profile: development
[cargo-make][1] INFO - Skipping Task: legacy-migration
[cargo-make][1] INFO - Skipping Task: maybe-start-server
[cargo-make][1] INFO - Skipping Task: maybe-start-client
[cargo-make][1] INFO - Build Done in 0.51 seconds.
2023-10-13T15:40:18.531331Z  INFO building client
[cargo-make][1] INFO - Calling cargo metadata to extract project info
warning: patch for `leptos` uses the features mechanism. default-features and features will not take effect because the patch dependency does not support this mechanism
warning: patch for `leptos_router` uses the features mechanism. default-features and features will not take effect because the patch dependency does not support this mechanism
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
[cargo-make][1] INFO - Cargo metadata done
    Blocking waiting for file lock on package cache
   Compiling proc-macro2 v1.0.67
   Compiling unicode-ident v1.0.12
   Compiling version_check v0.9.4
   Compiling once_cell v1.18.0
   Compiling wasm-bindgen-shared v0.2.87
   Compiling serde v1.0.188
   Compiling log v0.4.20
   Compiling bumpalo v3.14.0
   Compiling wasm-bindgen v0.2.87
   Compiling cfg-if v1.0.0
   Compiling thiserror v1.0.49
[cargo-make][1] INFO - Project: server   ] 3/211: wasm-bindgen(build.rs), serde(build.rs), proc-m...
[cargo-make][1] INFO - Build File: Makefile.toml
[cargo-make][1] INFO - Task: start
[cargo-make][1] INFO - Profile: development
[cargo-make][1] INFO - Skipping Task: legacy-migration
[cargo-make][1] INFO - Skipping Task: maybe-start-server
[cargo-make][1] INFO - Skipping Task: maybe-start-client
[cargo-make][1] INFO - Build Done in 0.53 seconds.
[cargo-make] INFO - Build Done in 3.13 seconds.
   Compiling autocfg v1.1.0
   Compiling memchr v2.6.4
   Compiling proc-macro-error-attr v1.0.4
➜  login_with_token_csr_only git:(main) ✗    Compiling proc-macro-error v1.0.4
   Compiling futures-core v0.3.28
   Compiling smallvec v1.11.1
   Compiling futures-channel v0.3.28
   Compiling unicode-xid v0.2.4
   Compiling futures-sink v0.3.28
   Compiling serde_json v1.0.107
   Compiling libc v0.2.148
   Compiling slab v0.4.9
   Compiling itoa v1.0.9
   Compiling futures-task v0.3.28
   Compiling quote v1.0.33
   Compiling ryu v1.0.15
   Compiling syn v2.0.37
   Compiling futures-util v0.3.28
   Compiling pin-project-lite v0.2.13
   Compiling proc-macro-utils v0.8.0
   Compiling lock_api v0.4.10
   Compiling proc-macro2-diagnostics v0.10.1
   Compiling xxhash-rust v0.8.7
   Compiling pin-utils v0.1.0
   Compiling const_format_proc_macros v0.2.31
   Compiling parking_lot_core v0.9.8
   Compiling futures-io v0.3.28
   Compiling manyhow-macros v0.8.1
   Compiling slotmap v1.0.6
   Compiling lazy_static v1.4.0
   Compiling ciborium-io v0.2.1
   Compiling anyhow v1.0.75
   Compiling yansi v1.0.0-rc.1
   Compiling camino v1.1.6
   Compiling half v1.8.2
   Compiling scopeguard v1.2.0
   Compiling tracing-core v0.1.31
   Compiling ciborium-ll v0.2.1
   Compiling collection_literals v1.0.1
   Compiling hashbrown v0.14.1
   Compiling async-trait v0.1.73
   Compiling equivalent v1.0.1
   Compiling same-file v1.0.6
   Compiling const_format v0.2.31
   Compiling prettyplease v0.2.15
   Compiling interpolator v0.5.0
   Compiling percent-encoding v2.3.0
   Compiling walkdir v2.4.0
   Compiling indexmap v2.0.2
   Compiling parking_lot v0.12.1
   Compiling getrandom v0.2.10
   Compiling aho-corasick v1.1.1
   Compiling either v1.9.0
   Compiling self_cell v1.0.1
   Compiling utf8-width v0.1.6
   Compiling regex-syntax v0.7.5
   Compiling base64 v0.21.4
   Compiling unicode-segmentation v1.10.1
   Compiling rustc-hash v1.1.0
   Compiling paste v1.0.14
   Compiling minimal-lexical v0.2.1
   Compiling convert_case v0.6.0
   Compiling html-escape v0.2.13
   Compiling wasm-bindgen-backend v0.2.87
   Compiling manyhow v0.8.1
   Compiling nom v7.1.3
   Compiling itertools v0.11.0
   Compiling wasm-bindgen-macro-support v0.2.87
   Compiling regex-automata v0.3.9
   Compiling uuid v1.4.1
   Compiling pathdiff v0.2.1
   Compiling itertools v0.10.5
   Compiling pad-adapter v0.1.1
   Compiling drain_filter_polyfill v0.1.3
   Compiling inventory v0.3.12
   Compiling common_macros v0.1.1
   Compiling regex v1.9.6
   Compiling serde_derive v1.0.188
   Compiling wasm-bindgen-macro v0.2.87
   Compiling thiserror-impl v1.0.49
   Compiling tracing-attributes v0.1.26
   Compiling derive-where v1.2.5
   Compiling futures-macro v0.3.28
   Compiling pin-project-internal v1.1.3
   Compiling js-sys v0.3.64
   Compiling pin-project v1.1.3
   Compiling syn_derive v0.1.7
   Compiling quote-use-macros v0.7.2
   Compiling tracing v0.1.37
   Compiling typed-builder-macro v0.16.2
   Compiling async-recursion v1.0.5
   Compiling rstml v0.11.2
   Compiling web-sys v0.3.64
   Compiling wasm-bindgen-futures v0.4.37
   Compiling quote-use v0.7.2
   Compiling attribute-derive-macro v0.8.1
   Compiling console_error_panic_hook v0.1.7
   Compiling typed-builder v0.16.2
   Compiling futures-executor v0.3.28
   Compiling futures v0.3.28
   Compiling attribute-derive v0.8.1
   Compiling serde-wasm-bindgen v0.5.0
   Compiling serde_qs v0.12.0
   Compiling ciborium v0.2.1
   Compiling server_fn_macro v0.5.1 (/Users/kevin/github_clones/leptos/server_fn_macro)
   Compiling leptos_hot_reload v0.5.1 (/Users/kevin/github_clones/leptos/leptos_hot_reload)
   Compiling toml v0.5.11
   Compiling serde_test v1.0.176
   Compiling api-boundary v0.0.0 (/Users/kevin/github_clones/leptos/examples/login_with_token_csr_only/api-boundary)
   Compiling linear-map v1.2.0
   Compiling config v0.13.3
   Compiling server_fn_macro_default v0.5.1 (/Users/kevin/github_clones/leptos/server_fn/server_fn_macro_default)
   Compiling leptos_config v0.5.1 (/Users/kevin/github_clones/leptos/leptos_config)
   Compiling leptos_macro v0.5.1 (/Users/kevin/github_clones/leptos/leptos_macro)
   Compiling gloo-utils v0.1.7
   Compiling leptos_reactive v0.5.1 (/Users/kevin/github_clones/leptos/leptos_reactive)
   Compiling console_log v1.0.0
   Compiling gloo-net v0.2.6
   Compiling gloo-storage v0.2.2
   Compiling server_fn v0.5.1 (/Users/kevin/github_clones/leptos/server_fn)
warning: `auto` traits are unstable
   --> /Users/kevin/github_clones/leptos/leptos_reactive/src/callback.rs:122:1
    |
122 | auto trait NotRawCallback {}
    | ^^^^
    |
    = note: see issue #13231 <https://github.com/rust-lang/rust/issues/13231> for more information
    = help: add `#![feature(auto_traits)]` to the crate attributes to enable
    = warning: unstable syntax can change at any point in the future, causing a hard error!
    = note: for more information, see issue #65860 <https://github.com/rust-lang/rust/issues/65860>

warning: `auto` traits are unstable
   --> /Users/kevin/github_clones/leptos/leptos_reactive/src/callback.rs:205:1
    |
205 | auto trait NotRawSyncCallback {}
    | ^^^^
    |
    = note: see issue #13231 <https://github.com/rust-lang/rust/issues/13231> for more information
    = help: add `#![feature(auto_traits)]` to the crate attributes to enable
    = warning: unstable syntax can change at any point in the future, causing a hard error!
    = note: for more information, see issue #65860 <https://github.com/rust-lang/rust/issues/65860>

warning: `auto` traits are unstable
   --> /Users/kevin/github_clones/leptos/leptos_reactive/src/signal_wrappers_read.rs:853:5
    |
853 |     auto trait NotSignalMarker {}
    |     ^^^^
    |
    = note: see issue #13231 <https://github.com/rust-lang/rust/issues/13231> for more information
    = help: add `#![feature(auto_traits)]` to the crate attributes to enable
    = warning: unstable syntax can change at any point in the future, causing a hard error!
    = note: for more information, see issue #65860 <https://github.com/rust-lang/rust/issues/65860>

   Compiling leptos_server v0.5.1 (/Users/kevin/github_clones/leptos/leptos_server)
   Compiling leptos_dom v0.5.1 (/Users/kevin/github_clones/leptos/leptos_dom)
warning: `leptos_reactive` (lib) generated 3 warnings
   Compiling leptos v0.5.1 (/Users/kevin/github_clones/leptos/leptos)
   Compiling leptos_meta v0.5.1 (/Users/kevin/github_clones/leptos/meta)
   Compiling leptos_router v0.5.1 (/Users/kevin/github_clones/leptos/router)
   Compiling client v0.0.0 (/Users/kevin/github_clones/leptos/examples/login_with_token_csr_only/client)
    Finished dev [unoptimized + debuginfo] target(s) in 27.61s
2023-10-13T15:40:46.210442Z  INFO fetching cargo artifacts
2023-10-13T15:40:46.454148Z  INFO processing WASM for client
2023-10-13T15:40:46.489098Z  INFO calling wasm-bindgen for client
2023-10-13T15:40:46.687350Z  INFO copying generated wasm-bindgen artifacts
2023-10-13T15:40:46.689570Z  INFO applying new distribution
2023-10-13T15:40:46.690329Z  INFO ✅ success
2023-10-13T15:40:46.692796Z  INFO 📡 serving static assets at -> /
2023-10-13T15:40:46.692807Z  INFO 📡 proxying /api/ -> http://127.0.0.1:3000/
2023-10-13T15:40:46.692862Z  INFO 📡 server listening at http://127.0.0.1:8080
2023-10-13T15:41:43.632031Z ERROR error handling request error=error proxying request to proxy backend

Caused by:
    0: error sending request for url (http://127.0.0.1:3000/users): error trying to connect: tcp connect error: Connection refused (os error 61)
    1: error trying to connect: tcp connect error: Connection refused (os error 61)
    2: tcp connect error: Connection refused (os error 61)
    3: Connection refused (os error 61)

Stack backtrace:
   0: std::backtrace::Backtrace::capture
   1: trunk::proxy::ProxyHandlerHttp::proxy_http_request::{{closure}}::{{closure}}
   2: <F as axum::handler::Handler<(M,T1,T2),S,B>>::call::{{closure}}
   3: <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll
   4: <axum::routing::route::RouteFuture<B,E> as core::future::future::Future>::poll
   5: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
   6: <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll
   7: <axum::routing::route::RouteFuture<B,E> as core::future::future::Future>::poll
   8: <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll
   9: <axum::routing::route::RouteFuture<B,E> as core::future::future::Future>::poll
  10: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_write
  11: <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
  12: <hyper::server::server::new_svc::NewSvcTask<I,N,S,E,W> as core::future::future::Future>::poll
  13: tokio::runtime::task::raw::poll
  14: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  15: tokio::runtime::task::raw::poll
  16: std::sys_common::backtrace::__rust_begin_short_backtrace
  17: core::ops::function::FnOnce::call_once{{vtable.shim}}
  18: std::sys::unix::thread::Thread::new::thread_start
  19: __pthread_deallocate
2023-10-13T15:41:43.652598Z ERROR response failed classification=Status code: 500 Internal Server Error latency=23 ms
```

This line is concerning, but don't have a server running on either 3000 or 8080 when this was started

```/var/folders/vd/1sbx_ywd60ncgn6lyhkjpqk80000gn/T/fsio_cx7egPjxCi.sh: line 6: [: too many arguments
  server is already started
```

I'm using the latest `main` branch as of today, but receiving other errors from leptos.  Either way it still appears to start both servers, but I receive the same errors.

As I said previously, I'm new to Rust, but have plenty of experience with other languages and trying to figure out what I'm missing.

FWIW, other examples like the the todo app run fine for me.

**Comment by gbj** [comment] 2023-11-24 19:21
Ok, so I was able to reproduce the issue, but realized that what was happening was that a different example was actually already running on `localhost:3000`, and was serving its `index.html` instead of the API response that should've been served by this example. Killing the process running that other example resolved the issue.

So I'm going to close this one.

**Closed by gbj** 2023-11-24 19:21 UTC

**Comment by kevinold** [comment] 2023-11-24 20:27
@gbj Glad you got it to work.  The problem persists for me even though I've confirmed that there is not another project running on port 3000.

**Comment by gbj** [comment] 2023-11-24 21:12
Okay — Well, what happens if you use cURL to send the same POST request that the Register form is trying to send? What response do you get?

**Comment by kevinold** [comment] 2023-11-24 21:37
![Screenshot 2023-11-24 at 3 36 21 PM](https://github.com/leptos-rs/leptos/assets/21967/e83b85fc-85f5-4319-876c-981aec599f35)

I get the same error with the connection refused, but originally the server started with out issue.

![Screenshot 2023-11-24 at 3 37 26 PM](https://github.com/leptos-rs/leptos/assets/21967/3b1b3a24-54fa-43a1-9bff-4f6ef045ecf8)

**Comment by gbj** [comment] 2023-11-24 22:14
That does not look to me like the server started successfully. That looks like trunk (the dev server for the frontend) started successfully, but errored out while trying to set up the proxy to the backend server (which is how this example works)
```
ERROR error handling request error=error proxying request to proxy backend
```
followed by a long backtrace coming from the server.

**Comment by kevinold** [comment] 2023-11-24 22:33
You're correct.  The server never starts for some reason.  I'm currently trying to diagnose *why* it never starts by clearing the cloned project and compiling everything fresh.  I'll report back.

**Comment by kevinold** [comment] 2023-11-25 00:08
I've clone the repo fresh and from the root of the project `cargo make` to build everything in the repo.  Then ran `cargo make start` inside of this example directory and I again experience the issue with the server not starting.

I'm honestly giving up trying to make it work at this point.  I've invested way to much time into trying to get an example to work.

**Comment by gbj** [comment] 2023-11-25 01:04
I'd suggest just running `trunk serve` in the client directory, and `cargo run` in the server directory, which should do the same thing for this one?

**Comment by kevinold** [comment] 2023-11-25 01:45
Thanks.  This technique worked and would have been one I'd tried if I could have deciphered that from the cargo make scripts.  Everything started as expected, no errors and the `/register` and `/login` forms worked.

**Comment by gbj** [comment] 2023-11-25 15:26
I should probably go through and add the "here's the simplest way to run this" for each example again. I think they were removed a little over-zealously while trying to standardize everything.
