### ISSUE TITLE
Bug with <For /> when using a struct array

### ISSUE THREAD

**Issue by cchance27** [leptos-rs/leptos#1802] opened 2023-09-29 00:46 UTC
**Describe the bug**
Getting lots of "component with id 1-0-40o not found, ignoring it for hydration" errors when i'm trying to use a <For /> when i've used a function to result in a function.

**Leptos Dependencies**
```toml
leptos = { git="https://github.com/leptos-rs/leptos.git", features = ["serde", "nightly"] }
leptos_axum = { git="https://github.com/leptos-rs/leptos.git", optional = true }
leptos_meta = { git="https://github.com/leptos-rs/leptos.git", features = ["nightly"] }
leptos_router = { git="https://github.com/leptos-rs/leptos.git", features = ["nightly"] }
```

**To Reproduce**
1. clone **https://github.com/cchance27/broken-leptos-forloop**
2. Run with cargo leptos watch
3. Goto http://localhost:3000

**Expected behavior**
For loop with the data from the serverfn remapped to a vec outputted in divs.

**Screenshots**
![image](https://github.com/leptos-rs/leptos/assets/13766359/2104165b-3370-49f4-8c78-182a05f07f4a)

**Additional context**
We discussed the issue on discord, heres the repo example

**Comment by gbj** [comment] 2023-09-29 13:09
Thanks. [This line](https://github.com/cchance27/broken-leptos-forloop/blob/c8ddeb2c4834bfff5d9124eff23a69eba9967a6f/src/app.rs#L50) is the issue: 
```rust
set_acct("111111".to_string());
```
This falls into a general category of "mutating state during server-side rendering is bad." Doing something like setting a signal in the body of a component function should more or less never make sense, because you can just use it as the initial value instead. In this particular example, updating the signal causes the resource to try to start loading a second time. I haven't dug into the particular mechanism that causes a bug, and it's possible that it would be possible to fix the bug; but the fact that it's broken is actually pointing to a serious inefficiency in your app. (For example, if the resource were doing something like making a DB request, you'd be hitting the DB twice for every render.) So I'm fine leaving it broken.

I think you confirmed on Discord that removing that `set_acct` and making it the initial value fixes the issue, so I'll close this.

**Closed by gbj** 2023-09-29 13:09 UTC
