### ISSUE TITLE
Inconsistent Hydration

### ISSUE THREAD

**Issue by MinaMatta98** [leptos-rs/leptos#830] opened 2023-04-07 21:24 UTC
Hello,

I believe I have encountered a form of inconsistent hydration.

Here is the code:

- create a server function:
```
#[server(ThumbnailRenderer)]
async fn render_thumbnails() -> Result<Vec<String>, ServerFnError> {
    let upload_path = std::fs::read_dir("./upload/thumbnails/").unwrap();
    Ok(upload_path
        .into_iter()
        .map(|items| {
            let path = items.unwrap().path();
            path.file_name().unwrap().to_str().unwrap().to_string()
        })
        .collect::<Vec<_>>())
}
```
- call upon the server function:
```
    let pdf_path = create_server_action::<Random>(cx);
    pdf_path.dispatch(Random {});
```
- call upon the last run value within view!:
```
        <section id="thumbnails" style="background-color: #212529; margin-top: 98px; height: calc(100% + 98px);"
            class=thumbnail_class>
                {move ||
                    thumbnail_list.value().get().map(|list|
                        view! {cx,
                           <For
                           each=move || list.clone().unwrap()
                           key=|thumbnail| thumbnail.to_owned()
                           view=move |cx, item| {
                             view! {
                               cx,
                                <div class="my-2" id=format!("/thumbnails/{item}")>
                                   <img src=format!("/thumbnails/{item}")
                                on:load=move|_| thumbnail_class_setter.set("position-fixed d-flex
                                flex-column overflow-scroll hover-overlay text-align-center px-3".to_string())
                                on:click=thumbnail_callback
                                />
                                </div>
                             }
                           }
                         />
                        })
                    }
        </section>
```
- Force an update by running the server function within an event handler:
```
 let on_submit_callback = move |event: SubmitEvent| {
....
thumbnail_list.dispatch(ThumbnailRenderer{});
}
```

Now, here's where I believe there is a problem, either with duplication of Elelements or work done within `<For/>` :

Most of the time, the UI updates normally upon submission:
![image](https://user-images.githubusercontent.com/81748812/230680176-9537d82a-f198-4dd1-94da-91d172680f61.png)

Sometimes, there is a duplication:
![image](https://user-images.githubusercontent.com/81748812/230680352-1ca76dfb-ad74-41f1-b0f0-950c1b27a4e4.png)
**Note that this disappears upon reload**

It is possible that this is due to an internal signal being updated within the code, however, it happens roughly once in every 7 submissions or so, without any specific pattern or difference between submissions. 

I'm aware that I can use a standard signal instead, but was wondering whether this behavior is expected by design.

**Comment by benwis** [comment] 2023-04-07 23:54
Out of curiosity, do you get a bunch of hydration warnings when you run this?

Looking at your example, I think you want a Resource instead of an Action here. Resources are used for getting data you want to appear on the page during SSR. Actions are more for tracking events, like if a user changes a post.

If you do use a Resource, you'll want to wrap the call to .read() it in a Suspense tag, like we do in our todo_app examples. This allows it to load the data on the server and stream down the result once down.
https://github.com/leptos-rs/leptos/tree/main/examples/todo_app_sqlite_axum

I don't know why you have that hydration behavior here, but I'm guessing it's a race condition kinda thing.

**Comment by MinaMatta98** [comment] 2023-04-08 02:12
Hello,

Thanks for the advice. I had already attempted this with create_local_resource and create_resource, but run into the same problem.

I am not getting a lot of hydration warnings, but there is **one**.

It's interesting that you believe it to be a race condition. From what I've noticed is that race conditions are more noticeable in consistent iterative calculations, I wouldn't have thought that a race condition would be happening at this frequency.

My initial suspicion was that it may have been a problem with hydration or within the For loop. 

My API is really simple and results in a file list being returned:

![image](https://user-images.githubusercontent.com/81748812/230698775-a978cbf5-ef0d-4ad5-9d8c-30809da376af.png)

I would like to note that within all the times where duplication has occurred, the post request has only been called once.

**Comment by gbj** [comment] 2023-04-08 11:17
I'm not able to reproduce any kind of issue with what you've provided. I had to do some work to get a compiling version because I'm a little confused because you refer to another server function `Random` and create a variable `pdf_path` that isn't used; I'm assuming this is supposed to be `ThumbnailRenderer` and that it should be used?

If you can provide some kind of minimal reproducible example of the behavior I'd be happy to take a look at it. Ben's advice to use `create_resource` is good in any case... if you ever find yourself creating and then immediately dispatching an action, a resource is probably the right decision.

**Comment by MinaMatta98** [comment] 2023-04-08 21:57
Hello,

Yes, I do not disagree.

I will break down exactly what's happening here:

This is a component that is responsible for producing the thumbnail view that I have listed:

```rust
#[component]
fn ThumbnailList(
    cx: Scope,
    pdf_iframe_setter: WriteSignal<String>,
    thumbnail_refresh: ReadSignal<bool>,
) -> impl IntoView {
    let (thumbnail_class, thumbnail_class_setter) = create_signal(
        cx,
        String::from(
            "position-fixed d-flex flex-column overflow-scroll hover-overlay text-align-center",
        ),
    );

    let thumbnail_list = create_local_resource(cx, thumbnail_refresh, move |_| async {
        render_thumbnails().await
    });

    let thumbnail_callback = move |event: MouseEvent| {
        let image = event.target().unwrap().unchecked_into::<HtmlImageElement>();
        let src = image.src();
        let id = src.split('/').last().unwrap().split('.').next().unwrap();
        pdf_iframe_setter.set(format!("/pdf/{id}"));
    };

    view! {cx,
        <section id="thumbnails" style="background-color: #212529; margin-top: 98px; min-height:100%; width: 150px"
            class=thumbnail_class>
            <Transition fallback=move|| view! {cx, "loading"}>
                {move ||
                    thumbnail_list.read(cx).map(|list|
                        view! {cx,
                           <For
                           each=move || list.clone().unwrap()
                           key=|thumbnail| thumbnail.to_owned()
                           view=move |cx, item| {
                             view! {
                               cx,
                                <div class="my-2 m-auto" id=format!("/thumbnails/{item}")>
                                   <img src=format!("/thumbnails/{item}")
                                on:load=move|_| thumbnail_class_setter.set("position-fixed d-flex
                                flex-column overflow-scroll hover-overlay text-align-center px-3".to_string())
                                on:click=thumbnail_callback
                                />
                                </div>
                             }
                           }
                         />
                        })
                    }
            </Transition>
        </section>
    }
}
```

It's dependencies are as follows:
```rust
    let (pdf_iframe, pdf_iframe_setter) = create_signal(cx, "".to_string());
    let (thumbnail_refresh, thumbnail_refresh_setter) = create_signal(cx, false);
```

The component is rendered within this view:

```rust
    styled::view! {cx, drag_styles(),
    <Router>
    <ThumbnailList pdf_iframe_setter thumbnail_refresh/>
    <h1 class="position-absolute w-75 start-50 translate-middle-x text-center p-5 mx-5">"Advanced Search Made Simple"</h1>
    <div id="status" style="display: none;"
        class="position-absolute w-75 start-50 translate-middle-x d-flex h-25 mx-5 my-3">
    </div>
    <div class="loading position-absolute start-50 bottom-50 my-5 translate-center-x mx-4" style="display: none;"
        id="loading-animation"></div>
     <div style="display: block ruby" class="position-absolute w-75 start-50 translate-middle-x bottom-50 h-25 mx-5 text-center my-5">
        {response}
     </div>
    <form method="post" action="/submit" enctype="multipart/form-data"
        style="justify-content: center; display: flex;  flex-direction: column"
        class="position-absolute w-75 start-50 translate-middle-x bottom-50 h-25 mx-5" id="form" on:submit=on_submit_callback>
        <div style="justify-content: center; display: flex;">
            <label class=upload_label for="file-input" id="uploadLabel">"choose alternative file"</label>
            <input _ref=file_input_ref id="file-input" type="file" class="upload" name="file-input" accept="application/pdf" on:change=submit_button_handler />
        </div>
        <br />
        <div style="justify-content: center; display: flex;">
            <input type="remove" id="remove-button" value="remove" class="uploadLabel display-box removeBox" on:click=remove_callback />
        </div>
        <div style="justify-content: center; display: flex;">
            <input type="view" id="view-button" value="view" class="uploadLabel display-box removeBox" />
        </div>
        <br />
        <div style="justify-content: center; display: flex;">
            <input type="submit" id="submit-button" value="submit" style=submit_button class=submit_button_class/>
        </div>
    </form>
    <br />
    <div>
        <section id="showcase" class="w-75 position-absolute start-50 translate-middle-x top-50 h-auto mx-5">
                {move || { pdf_path.value().get().map(|val| {
                view! {cx,
                <iframe _ref=iframe_ref id="iframe" width="100%" height="100%" frameborder="0" allowfullscreen src={
                    pdf_iframe_setter.set("/pdf/".to_string() + &val.unwrap().unwrap());
                pdf_iframe}/>
                }})}}
        </section>
    </div>
        </Router>
    }

```

Here is the main functionality. You submit a pdf view the input (_ref=file_input_ref), it results in the following on submit callback:

```rust
    pub fn submit_callback<'a>(
        file_input_ref: NodeRef<Input>,
        response_setter: WriteSignal<leptos::Fragment>,
        cx: Scope,
        thumbnail_refresh_setter: Option<WriteSignal<bool>>,
        submit_button_setter: Option<WriteSignal<&'a str>>,
        upload_label_setter: Option<WriteSignal<&'a str>>,
        toggle: Option<WriteSignal<bool>>
    ) -> impl Fn(SubmitEvent) {
        move |event: SubmitEvent| {
            event.stop_propagation();
            event.prevent_default();

            let file_input = file_input_ref.get().expect("could not capture file input");

            let file = file_input.files().unwrap().get(0).unwrap();

            let buffer = file_to_u8(file);

            spawn_local(async move {
                let buffer = buffer.await.unwrap();

                let result = Request::post("/submit").body(&buffer).send().await.unwrap();

                if result.ok() {
                    response_setter.set(view! {cx,
                          <p class="mx-1">"File Uploaded Successfully "</p>
                          <i class="fas fa-check-circle text-success" style="font-size: 1em"></i>
                });
                    if let Some(refresher) = thumbnail_refresh_setter {
                        refresher.update(|value: &mut bool| *value = !*value);
                    }

                    if let Some(toggle) = toggle {
                        toggle.update(|val: &mut bool| *val = !*val);
                    }

                } else {
                    let response_text = result.text().await.unwrap();

                    response_setter.set(view! {cx,
                          <p class="mx-1">{response_text}</p>
                          <i class="fas fa-circle-xmark text-danger" style="font-size: 1em"></i>
                    });
                }

                if let Some(setter) = submit_button_setter {
                    setter.set("display:none");
                }

                if let Some(setter) = upload_label_setter {
                    setter.set("uploadLabel display-box");
                }
            })
        }
    }
```

Basically, a post request that results in a pdf being stored and thumbnails being produced via cairo-rs is made. The callback also sends an update signal to re-render the ThumbnailList. which returns all the available thumbnails and is used to create the <For/> loop.

```rust
#[post("/submit")]
pub async fn upload_server(mut form_data: Payload) -> Result<String, std::io::Error> {
    use futures_util::StreamExt;

    let timestamp = std::time::SystemTime::now()
        .duration_since(std::time::SystemTime::UNIX_EPOCH)
        .unwrap()
        .as_secs();

    let pdf_path = format!("upload/{}{}", timestamp, ".pdf");

    let pdf_thumbnail_path = format!("upload/thumbnails/{}{}", timestamp, ".png");

    let mut bytes = BytesMut::new();

    while let Some(item) = form_data.next().await {
        bytes.extend_from_slice(&item.expect("Internal Server Error. Try again in a few minutes"));
    }

    std::fs::write(&pdf_path, bytes)?;

    create_thumbnail(
        std::path::Path::new(&pdf_path),
        std::path::Path::new(&pdf_thumbnail_path),
    )
    .await?;
    Ok(String::from(""))
    // Err(std::io::Error::new(std::io::ErrorKind::Other, "error"))
}
```

I don't expect you to reproduce this, I am happy to send you a minimal viable product, but I don't know if it is worth your time going through this. I thought that this would be an issue that you have encountered previously.

**Comment by gbj** [comment] 2023-04-10 12:01
I'd like to help fix this but unfortunately am not able to because there are so many missing pieces. I've created a couple different versions to try it out, but have not been able to reproduce any kind of issue. I'd be very happy to look at either a minimal reproduction or a repository with the actual application and try to see what's going on, but I'm going to close this for now.

**Closed by gbj** 2023-04-10 12:01 UTC
Labels: needs reproduction
