### ISSUE TITLE
0.5.0-beta Attempted to get a memo after it was disposed

### ISSUE THREAD

**Issue by johan-smits** [leptos-rs/leptos#1488] opened 2023-08-03 09:24 UTC
**Describe the bug**

**Leptos Dependencies**

```toml
leptos = { version = "0.5.0-alpha2", default-features = false, features = ["serde", "nightly"] }
leptos_router = { version = "0.5.0-alpha2", default-features = false }
```

**To Reproduce**

```rs
    let app_state = expect_context::<RwSignal<AppState>>();

    let (token, _) = create_slice(
        // we take a slice *from* `state`
        app_state,
        // our getter returns a "slice" of the data
        |state| state.token,
        // our setter describes how to mutate that slice, given a new value
        |state, token| state.token = token,
    );
```

Open your app and it will show the error.

**Expected behavior**
Don't panic.

**Screenshots**
![image](https://github.com/leptos-rs/leptos/assets/3228882/267aba2e-c367-4032-a9dd-6d6e89943c43)

**Additional context**
This code works in the `0.4.5` version.

**Comment by gbj** [comment] 2023-08-03 11:18
Unfortunately the reproduction you've provided is not, on its own, sufficient to reproduce the issue. Below is one attempt to reproduce it based on what you've given, which doesn't panic.

If you could provide a minimal example that does reproduce the panic I'd be happy to take a look at it.

```rust
#[derive(Copy, Clone, PartialEq, Debug, Default)]
struct AppState {
    token: u32,
}

#[component]
pub fn App() -> impl IntoView {
    provide_context(create_rw_signal(AppState::default()));

    view! { <Child/> }
}

#[component]
pub fn Child() -> impl IntoView {
    let app_state = expect_context::<RwSignal<AppState>>();

    let (token, _) = create_slice(
        // we take a slice *from* `state`
        app_state,
        // our getter returns a "slice" of the data
        |state| state.token,
        // our setter describes how to mutate that slice, given a new value
        |state, token| state.token = token,
    );

    token
}
```

**Comment by johan-smits** [comment] 2023-08-03 11:27
@gbj I saw creating a test case that the `<Redirect path="/dash"/>` causes it.

Example:

```rs
#[derive(Serialize, Deserialize, Default, Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct Token {
    pub id: i32,
    pub account_id: i32,
}

#[derive(Serialize, Deserialize, Default, Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct AppState {
    pub token: Option<Token>,
}

async fn fetch_token() -> Result<Token, reqwasm::Error> {
    Ok(Token {
        id: 1,
        account_id: 1,
    })
}

#[component]
fn App() -> impl IntoView {
    let (is_routing, set_is_routing) = create_signal(false);
    let app_state = expect_context::<RwSignal<AppState>>();

    let (token, _) = create_slice(
        // we take a slice *from* `state`
        app_state,
        // our getter returns a "slice" of the data
        |state| state.token,
        // our setter describes how to mutate that slice, given a new value
        |state, token| state.token = token,
    );

    view! {
      <RoutingProgress
        is_routing
        max_time=std::time::Duration::from_millis(250)
        class="RoutingProgress"
      />
      <Router set_is_routing>
        <Routes>
          <ProtectedRoute
            path=Routes::Login::path()
            redirect_path="/login"
            condition=move || token().is_none()
            view=Login
          />
          <ProtectedRoute
            path="/*"
            redirect_path="/dash"
            condition=move || token().is_some()
            view=Application
          >
            <Route path="" view=|| view! {  <Redirect path="/dash"/> }/>
          </ProtectedRoute>
        </Routes>
      </Router>
    }
}

#[component]
fn Main() -> impl IntoView {
    let app_state: RwSignal<AppState> = create_rw_signal(AppState { token: None });
    provide_context(app_state);

    let token = create_resource(
        || (),
        move |_| async move {
            log::debug!("loading token from API");
            match fetch_token().await {
                Ok(token) => {
                    app_state.set(AppState { token: Some(token) });
                    Some(token)
                }
                Err(_) => None,
            }
        },
    );

    view! {
      <Suspense fallback=move || {
          view! {  <Loading/> }
      }>{move || { token.read().map(|_| view! {  <App/> }) }}</Suspense>
    }
}

fn main() {
    console_error_panic_hook::set_once();
    if production() {
        console_log::init_with_level(log::Level::Info).unwrap();
    } else {
        console_log::init_with_level(log::Level::Debug).unwrap();
    }

    mount_to_body(|| view! {  <Main/> })
}
```

**Comment by gbj** [comment] 2023-08-03 13:25
Okay, I see. This is fundamentally another issue due to having `<Router>` inside a `<Suspense>`.

I found that if I simply move the `Router` component so that `<Router>` wraps the `<Suspense>` in `<Main>`, rather than wrapping the `<Routes>` in `<App>`, it works as expected. Does that appear to work for you, too?

**Comment by johan-smits** [comment] 2023-08-04 06:46
Some information we spoke about on the chat:

```diff
 #[component]
 fn Main() -> impl IntoView {
+    let (is_routing, set_is_routing) = create_signal(false);
     let app_state: RwSignal<AppState> = create_rw_signal(AppState { token: None });
     provide_context(app_state);
 
@@ -124,9 +117,16 @@ fn Main() -> impl IntoView {
     );
 
     view! {
+      <RoutingProgress
+        is_routing
+        max_time=std::time::Duration::from_millis(250)
+        class="RoutingProgress"
+      />
+      <Router set_is_routing>
       <Suspense fallback=move || {
           view! { <Loading/> }
       }>{move || { token.read().map(|_| view! { <App/> }) }}</Suspense>
+      </Router>
     }
 }
```

I get it always even with your suggested change, nou need to trigger the route which triggers the Redirect on this line: `<Route path="" view=|| view! {  <Redirect path="/dash"/> }/>`. If I remove the redirect and just put `<Route path="" view=|| { view! { "HI" } } />` it does not panic. And the route is then `/` from the browser that should become `/dash/`

**Comment by aschey** [comment] 2023-08-08 03:57
I'm working on a custom framework built on top of `leptos_reactive` and I ran into this as well. I was able to reproduce using a rather contrived, but fairly minimal example. The error seems to occur here: https://github.com/leptos-rs/leptos/blob/8e03c00a369635d0c15b0c9469b82f737323e9c9/leptos_reactive/src/runtime.rs#L157 If that line is commented out, the error goes away.

```rust
use leptos_reactive::{create_effect, create_runtime, create_signal, prelude::*};
use std::{cell::OnceCell, error::Error, rc::Rc};

fn main() -> Result<(), Box<dyn Error>> {
    let _rt = create_runtime();

    let (sig, set_sig) = create_signal(0);

    let counter_cache: OnceCell<Rc<dyn Fn()>> = OnceCell::new();
    let counter = move || {
        let (count, set_count) = create_signal(0);
        create_effect(move |_| {
            set_count.update(|c| *c += sig.get());
        });

        counter_cache
            .get_or_init(|| {
                Rc::new({
                    move || {
                        println!("count {0}", count.get());
                    }
                })
            })
            .clone()
    };

    let counter_wrapper = move || {
        move || {
            let c = counter();
            move || {
                c();
            }
        }
    };

    let c = counter_wrapper();
    create_effect(move |_| {
        c()();
    });

    set_sig.update(|s| *s += 1);

    Ok(())
}
```

**Comment by aschey** [comment] 2023-08-08 13:24
Apologies, I thought the root cause might be the same, but you're right, I'm not totally sure.

**Comment by johan-smits** [comment] 2023-08-11 07:23
I'm was able to make a minimal reproducible [example](https://github.com/johansmitsnl/leptos-test/tree/attempted-to-get-memo-after-it-was-disposed)

Just open the browser at `http://127.0.0.1:8080/` and you see the panic. I would expect I was redirected to `http://127.0.0.1:8080/dash` due to this code [line](https://github.com/johansmitsnl/leptos-test/blob/dda0fd2b70492e8d23e3a4ff81bb939905595ff9/src/main.rs#L64)

**Comment by gbj** [comment] 2023-08-11 11:30
Writing to a signal inside a resource read, then taking a memoized slice of that signal, and then reading from that memo inside a Suspense, all just seems very odd to me.

Here's one much more straightforward way to do it, which is simply to read from the memo in the Suspense in Main and pass the value of the token into the App as a prop:
```rust
#[component]
fn App(token: Option<Token>) -> impl IntoView {
    view! {

        <Routes>
          <ProtectedRoute
            path="/login"
            redirect_path="/dash"
            condition=move || token.is_none()
            view=|| view! { "Login page" }
          />
          <ProtectedRoute
            path="/*"
            redirect_path="/login"
            condition=move || token.is_some()
            view=|| view! { <p>"Dash page"</p><Outlet/> }
          >
            <Route path="" view=|| view! {  <Redirect path="/dash"/> }/>
            <Route path="/dash" view=|| view! {  <p>"I'm on the dash page now"</p> }/>
          </ProtectedRoute>
        </Routes>
    }
}

#[component]
fn Main() -> impl IntoView {
    let (is_routing, set_is_routing) = create_signal(false);

    let token = create_resource(
        || (),
        move |_| async move {
            log::debug!("loading token from API");
            fetch_token().await.ok()
        },
    );

    view! {
      <RoutingProgress
        is_routing
        max_time=std::time::Duration::from_millis(250)
        class="RoutingProgress"
      />
      <Router set_is_routing>
        <Suspense fallback=move || {
            view! {  "Loading..." }
        }>
          {move || {
            token.read()
              .map(|token| view! { <App token/> }) }
          }
        </Suspense>
      </Router>
    }
}
``` 

Here's an alternate version of the Main component that's more similar in structure to your existing version, but use `spawn_local` to simply run the future and set the signal rather than creating a resource and using suspense.

```rust
#[component]
fn Main() -> impl IntoView {
    let app_state: RwSignal<AppState> = create_rw_signal(AppState { token: None });
    provide_context(app_state);

    spawn_local(async move {
        log::debug!("loading token from API");
        if let Ok(token) = fetch_token().await {
            app_state.set(AppState { token: Some(token) });
        }
    });

    view! { <App/> }
}
```

At this point I don't think I'd really consider this a bug for me to fix in the framework. The two natural solutions are
1. Create a resource and read its value under Suspense, and pass that value to the other component
2. Spawn a future to do the async work, and set the signal value, and read that signal value in the other component

Both of them work fine.

**Comment by johan-smits** [comment] 2023-08-11 12:24
Why should you use `spawn_local` and not `create_resource`?

With this change what I see now is that I keep stuck at the login page. I have made the change in a new [commit](https://github.com/johansmitsnl/leptos-test/blob/03a098bc4867c96388b683c2e431edf2c2e5dcfc/src/main.rs#L79). This was the reason why I used the Suspense since I want to have a loading spinner and switch to the app when fully loaded. Why is the `<Redirect path="/dash"/>` triggering the issue in my original example the error?

**Comment by gbj** [comment] 2023-08-11 15:26
> With this change what I see now is that I keep stuck at the login page. I have made the change in a new [commit](https://github.com/johansmitsnl/leptos-test/blob/03a098bc4867c96388b683c2e431edf2c2e5dcfc/src/main.rs#L79). This was the reason why I used the Suspense since I want to have a loading spinner and switch to the app when fully loaded.

Well, you've set the app up to redirect to the login page if the token is `None`, which is always true initially before it's loaded. Maybe what you really want is to redirect if the token is `None(None)`?

**Comment by johansmitsnl** [comment] 2023-08-12 06:02
You mean wrapping the appstate in a option?

**Comment by gbj** [comment] 2023-08-12 12:14
> You mean wrapping the appstate in a option?

You're right, the version with `spawn_local` and setting a signal doesn't distinguish between the loading state `None` and the no-user state. You really only want to redirect in the no-user state. I was thinking of my first suggested version, with the resource, and I really should have said you're checking for `Some(None)`, as this would mean the resource had loaded and contains no token.

**Comment by johansmitsnl** [comment] 2023-08-12 15:40
Ok, so when I do the first option, making a slide somewhere in a deeper component of the token that will not be an issue as it is the same we run into now?

**Comment by gbj** [comment] 2023-08-13 12:34
Correct. It should not cause the same issue.

I'm going to close this as completed, feel free to open a future discussion here or on GitHub if you run into issues.

**Closed by gbj** 2023-08-13 12:34 UTC

**Comment by johan-smits** [comment] 2023-08-15 08:46
Did a [refactor](https://github.com/johansmitsnl/leptos-test/blob/attempted-to-get-memo-after-it-was-disposed/src/main.rs) and this works. Thanks for the support :+1:

Although the way I did it was logical to me since it also compiled and only the redirect piece prevent it from working.
